/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n8.0.1-55-g59384ce6b6-20260207"
#endif /* AVUTIL_FFVERSION_H */
