#pragma once
// DJMax Online Song Database - Auto-generated
// Total: 277 songs

struct DJMaxSongEntry {
    const char* tag;
    const char* title;
    const char* composer;
    const char* artist;
    int bpm;
};

static const DJMaxSongEntry DJMAX_SONG_DB[] = {
    {"1stsync", "1st-sync", "Forte Escape", "Kinys", 140},
    {"ai", "A ．I", "Forte Escape", "Kinys", 138},
    {"asunshine", "Again Sunshine", "Forte Escape", "Kinys", 161},
    {"alliwant", "All I want", "Wasabi iceCream", "none", 140},
    {"allofyourlove", "All of your love", "Wasabi iceCream", "none", 130},
    {"anight", "Arabian Night", "East Wind", "none", 130},
    {"astro", "Astro Fight", "Forte Escape", "ECO", 183},
    {"aurora", "Aurora Borealis", "Electronic Boutique", "none", 153},
    {"braveitout", "Brave it out", "GonZo", "Tina", 124},
    {"brightdreamvc", "Bright Dream", "M2U", "Tari&Eter", 130},
    {"brightdreamins", "Bright Dream", "M2U", "none", 130},
    {"canremix", "Can we talk", "Forte Escape", "none", 130},
    {"canwetalk", "Can We Talk", "Forte Escape", "Aqualix", 125},
    {"carmenfantasy", "Carmen Fantasy", "荤扼荤抛", "none", 150},
    {"carmentoreador", "Carmen Toreador", "厚力", "none", 151},
    {"catchme", "Catch Me", "Forte Escape", "Arms", 145},
    {"celestial", "Celestial Tears", "Tsukasa", "RB", 165},
    {"cog", "Chains of Gravity", "Tsukasa", "JAY", 155},
    {"chase575", "Chase 575", "Forte Escape", "Kinys", 170},
    {"cherokee", "Cherokee", "xxdbxx", "none", 136},
    {"chronobreakers", "Chrono Breakers", "NieN", "RESS", 178},
    {"cnp", "CnP", "CrooFE", "none", 127},
    {"coolrunning", "Cool Running", "East Wind", "none", 106},
    {"cosmicelevator", "Cosmic Elevator", "Forte Escape", "none", 164},
    {"caikospost", "Csikos Post", "Necke", "Eyehead", 160},
    {"damascus", "Damascus", "makou", "none", 118},
    {"dplanet", "Dancin＇ Planet", "Planetboom", "none", 132},
    {"detonator", "Detonator", "EarBreaker", "ECO", 160},
    {"dreadnought", "Dreadnought", "EarBreaker", "ECO", 140},
    {"dreamofyou", "Dream Of You", "makou", "Eyehead", 192},
    {"elasticstar", "Elastic Star", "Forte Escape", "Eyehead", 132},
    {"elasticstar", "Elastic Star", "Forte Escape", "Eyehead", 132},
    {"electrosens", "Electro Sensibility", "Forte Escape", "ECO", 132},
    {"endofmoon", "End of the Moonlight", "Forte Escape", "US", 155},
    {"enemystorm", "Enemy storm", "Croove", "none", 133},
    {"boy", "Eternal Memory (少女的梦)", "M2U", "NG", 125},
    {"extreme", "Extreme Z4", "Forte Escape", "Kinys", 152},
    {"fangel", "FallenAngel", "DJ Mocha", "Tari&Eter", 142},
    {"fear", "Fear", "酱欺部付", "Tina", 182},
    {"feel", "Feel", "DJ Mocha", "NB5", 124},
    {"fentanest", "Fentanest", "EarBreaker&eszett", "Tari&Eter", 160},
    {"fevergj", "Fever GJ", "xxdbxx", "Eyehead", 98},
    {"fseasons", "For Seasons", "makou", "Tari&Eter", 116},
    {"ikarus", "For the ikarus", "NieN", "BAILKNIGHT", 154},
    {"ftr", "FTR", "酱欺部付", "Tari&Eter", 140},
    {"funkychups", "Funky Chups", "Forte Escape", "Eyehead", 127},
    {"futurerism", "Futurism", "Forte Escape", "NG", 142},
    {"getontop", "Get On Top", "Planetboom", "Eyehead", 125},
    {"getup", "Getup", "Croove", "Catty", 135},
    {"gridsystem", "Grid System", "Tsukasa", "Kimys&ECO", 146},
    {"hellowchristmas", "Hello christmas", "East Wind", "none", 143},
    {"pinky", "Hello Pinky", "NieN", "Tari&Eter", 141},
    {"hey", "Hey! there", "Forte Escape", "Hye-ra", 127},
    {"hypersonic", "Hypersonic", "xxdbxx", "BS", 134},
    {"jbg", "JBG", "Croove", "Eyehead", 102},
    {"jupiter", "Jupiter Driving", "xxdbxx", "Eyehead", 144},
    {"ksystem", "Knowledge system", "Forte Escape", "NG", 140},
    {"kuda", "KUDA", "GonZo", "NG", 126},
    {"lemonade", "Lemonade", "M2U", "Tari&Eter", 195},
    {"letgo", "Let Go", "xxdbxx", "Panax", 102},
    {"letsgobaby", "Let`s Go Baby", "3rd Coast", "Miyu", 108},
    {"lighthouse", "Light House", "xxdbxx", "ECO", 162},
    {"livingon", "Living on The Beat", "Forte Escape", "none", 147},
    {"longvacation", "Long Vacation", "ESTi", "Tari", 138},
    {"luvflow", "Luv Flow", "3rd Coast", "Ayamy", 115},
    {"masai", "MASAI", "Croove", "ECO", 128},
    {"memoryofbeach", "Memory of Beach", "M2U", "AP", 130},
    {"messitup", "Mess it Up", "Nauts (N-Square)", "Tari&Eter", 140},
    {"mblood", "MidNight Blood", "NieN", "Tako Ashin", 147},
    {"miles", "miles", "Electronic Boutique", "NONE", 130},
    {"minimallife", "Minimal Life", "EarBreaker", "ECO", 145},
    {"mojosong", "Mojo song", "Wasabi iceCream", "none", 135},
    {"myalias", "My Alias", "Dayz", "Panax", 110},
    {"nbvsnb", "NB POWER", "NieN", "ECO", 185},
    {"nbranger", "NB Ranger", "M2U", "Ponglow&ECO&Tari&NG", 140},
    {"neversay", "Never Say", "ND Lee", "Eyehead", 90},
    {"oblivion", "Oblivion", "ESTi", "D-myo", 141},
    {"on", "ON", "ND Lee", "RB", 72},
    {"onesidedlove", "One Sided Love", "Electronic Boutique", "Kaho", 90},
    {"onethelove", "One The Love", "xxdbxx", "Eyehead", 125},
    {"outlaw", "Out Law", "Croove", "D", 126},
    {"paraq", "Para Q", "Forte Escape", "ECO", 160},
    {"pos", "Phantom Of Sky", "M2U", "Choi", 115},
    {"phoenix", "Phoenix Virus", "M2U", "Kinys&ECO&Eter", 140},
    {"rayof", "Ray of Illuminati", "ESTi", "Tari Eter Eco", 150},
    {"realoverdrive", "Real Over Drive", "NieN", "Zett", 152},
    {"red", "Red", "Croove", "Tari&Eter", 128},
    {"relationagain", "Relation Again(ESTi`s Remix)", "Tsukasa&ESTi", "Tari&Eter", 135},
    {"revenge", "Revenge", "ND Lee", "none", 120},
    {"riverflow", "River Flow", "Planetboom", "Ayamy", 175},
    {"roadofdeath", "Road of Death", "NieN", "necobus", 180},
    {"rockordie", "Rock or Die", "NieN", "BS", 106},
    {"rocka", "Rocka-a-doodle-doo", "makou", "none", 135},
    {"rolling", "Rolling on the duck", "NieN", "JAY", 180},
    {"russiandnc", "Russian Dance", "Tchaikovsky", "none", 155},
    {"samba", "Samba Samba", "Wasabi iceCream", "none", 170},
    {"savemydream", "Save My Dream", "Forte Escape", "Napa", 125},
    {"schoolsomeday", "School Someday", "Electronic Boutique", "Kaho", 125},
    {"seeker", "Seeker", "M2U", "Ayamy", 150},
    {"sin2", "SIN", "ESTi", "RESS", 190},
    {"sneakers", "Sneakers", "East Wind", "none", 100},
    {"spaceofsoul", "Space of Soul", "M2U", "none", 160},
    {"spygirl", "Spy Girl", "Wasabi iceCream", "none", 160},
    {"starfish", "Starfish", "Planetboom", "Tari&Eter", 150},
    {"stars", "Stars in your eyes", "bermei inazawa", "nineteen", 100},
    {"sunnyside", "Sunny side", "Croove", "TIV", 112},
    {"superlovely", "Super Lovely", "EarBreaker", "Soryu", 170},
    {"tammuz", "Tammuz", "Forte Escape", "ECO", 140},
    {"temptation", "Temptation", "S-TRO", "Eyehead", 136},
    {"toofast", "Too Fast", "Forte Escape", "onieye", 107},
    {"triple", "Triple Zoe", "Forte Escape", "ECO", 150},
    {"unight", "Urban Night", "Electronic Boutique", "Tina", 124},
    {"vlady", "Vanish Lady", "Electronic Boutique", "none", 145},
    {"vbob", "V-BOB", "Forte Escape", "Tari", 150},
    {"virgin", "Virgin", "Ban Claf", "none", 120},
    {"weirdpistol", "WeirdPistol", "Forte Escape", "none", 122},
    {"yaparty", "Ya! Party!", "Forte Escape", "Tari&Eter", 194},
    {"yellowberry", "Yellowberry", "Forte Escape", "Tari", 161},
    {"yocreoquesi", "Yo Creo Que Si", "makou", "ECO", 135},
    {"yomax", "Yomax", "ND Lee", "Sonar", 72},
    {"chai", "钢琴协奏曲第1号", "瞒捞内橇胶虐", "none", 156},
    {"symphony40", "葛莫扎特40号交响曲第一章", "葛楼福飘", "none", 135},
    {"trumpet", "海顿小号协奏曲快板 3", "窍捞电", "none", 150},
    {"morning", "美丽晨光", "ND Lee", "D-myo", 150},
    {"summer3", "四季-夏 第三乐章", "厚惯叼", "ECO", 150},
    {"turkey", "土耳其进行曲", "葛楼福飘", "none", 140},
    {"baram", "微风祈愿", "Forte Escape", "Tako Ashin", 108},
    {"baramlive", "微风祈愿(Live ver)", "Forte Escape", "NG&BS", 210},
    {"summerdream", "仲夏夜之梦", "膏胆胶粮", "none", 126},
    {"wuha", "WUHA", "毕国勇", "PAPA", 126},
    {"tcj", "太刺激 2007", "司文", "Name.RED", 124},
    {"perseus", "英仙座 Remix", "金镇", "PAPA", 143},
    {"yxz", "樱雪座", "金镇", "PAPA", 155},
    {"sakura", "桜華月", "AKITO", "None", 155},
    {"eol", "终结孤单", "阿信", "PAPA", 200},
    {"1st", "1st", "冠傣沥", "Eyehead", 116},
    {"angel", "ANGEL", "Jeppet", "Tari", 124},
    {"angelictears", "Angelic Tears", "SHIKI", "Kimys&ShininG&Eter", 146},
    {"anotherlove", "Another Love", "捞沥绕", "NONE", 127},
    {"avemaria", "Avemaria", "Schubert", "none", 158},
    {"bananashake", "Banana shake", "捞瘤赴", "NONE", 126},
    {"bingo", "BINGO", "冠己柳", "none", 150},
    {"binbingo", "Bin-Go", "倾犁酋", "none", 120},
    {"bobjo", "BobJo", "捞犁铰", "NONE", 105},
    {"brandnew", "Brand New", "冠辟怕&炼康荐", "none", 103},
    {"crazy", "Crazy", "辫档泅&Perry", "none", 110},
    {"dancedance", "Dance Dance", "1TYM 价归版", "NONE", 102},
    {"delicious", "Delicious humming", "捞瘤赴", "NONE", 124},
    {"discoking", "Disco King", "高耀太", "none", 125},
    {"discotime", "Disco Time", "M2U", "Tari", 130},
    {"bajo", "ela(bajo de la luna)", "lee juno&lee jinwook", "none", 126},
    {"eros", "Eros", "林康绕", "none", 102},
    {"eternity", "Eternity", "沥犁屈", "none", 120},
    {"far", "FarEast GlassField", "I．B．I．S", "none", 145},
    {"from", "From", "剧康绕", "none", 80},
    {"girls", "Girls", "Perry", "none", 123},
    {"happyface", "Happy Face", "S．Murayama", "NONE", 98},
    {"im", "IM", "剧康绕", "Ayamy", 165},
    {"letmedance", "Let Me Dance", "轿捞欺", "none", 110},
    {"maybe", "Maybe", "冠傣沥", "Tari", 75},
    {"carol2", "Merry christmas ...", "none", "ECO", 96},
    {"moto", "MOTO", "Kenzie", "none", 112},
    {"myname", "MY NAME", "Kenzie", "none", 110},
    {"oh", "Oh!", "捞刮快", "none", 101},
    {"pleez", "Pleeez", "绊康券", "D", 102},
    {"rain", "Rain", "Jeppet", "ECO", 130},
    {"reallife", "Real Life", "绊康券", "NONE", 100},
    {"regret", "Regret of snow", "SHIKI", "none", 186},
    {"relax", "Relax", "mAd sOuL cHiLd", "none", 96},
    {"reload", "Reload", "篮瘤盔", "none", 105},
    {"risingsun", "Rising sun", "蜡康柳", "none", 125},
    {"carol1", "Rudolf", "none", "Eyehead", 137},
    {"sakura", "Sakurakagetsu", "AKITO", "Tari&Eter", 138},
    {"saymylove", "Say My Love", "JJ Groove", "D", 175},
    {"scullyk", "Scully Doesn`t Know", "捞瘤赴", "NONE", 120},
    {"steppingout2", "STEPPING OUT-STEP REMIX-", "辫己绕", "NONE", 130},
    {"sweet", "Sweet", "lee juno&lee jinwook", "none", 128},
    {"sweetlove", "Sweet Love", "M2U", "Ayamy", 140},
    {"thegirl", "The girl is mine(feat Lisa)", "辫怕泅", "none", 96},
    {"tokyo", "The Tokyo", "I．B．I．S", "none", 143},
    {"together", "Together", "高耀太", "none", 144},
    {"triangle", "Tri-Angle", "东方神起", "none", 90},
    {"windy", "Windy", "倾犁酋", "Sonar", 120},
    {"withoutyourlove", "Without Your Love", "厘快酋", "none", 134},
    {"lnight2", "悲哀的祈祷 赢", "何劝", "none", 103},
    {"bisoo", "匕首", "蜡己痹", "none", 100},
    {"pizzicato", "拨弦波尔卡", "酱飘扼快胶", "none", 130},
    {"songofspring", "春天之歌", "MendelsSohn", "none", 145},
    {"fromnow", "从现在起", "高耀太", "none", 148},
    {"phone", "电话号码", "TEDDY", "none", 88},
    {"animal", "动物嘉年华", "积惑胶", "none", 110},
    {"dannyum", "放弃", "冠辟枚", "NONE", 120},
    {"crazy2", "疯狂(Crazy)", "炼康荐", "none", 93},
    {"storm", "暴风雪山", "炔技霖", "NONE", 138},
    {"fire", "火花", "高耀太", "none", 142},
    {"bravo", "欢呼", "蜡己痹", "none", 100},
    {"idiot", "蝗虫", "Perry", "none", 109},
    {"passion", "情感", "TEDDY", "none", 101},
    {"chopmarch", "筷子", "Rielly", "none", 160},
    {"dreammeet", "梦见", "辣籍霖", "none", 93},
    {"slowwalk", "慢慢地走", "捞侩刮", "none", 140},
    {"owl", "猫头鹰", "捞力捞", "none", 94},
    {"sister", "妹妹的梦", "Dan Blan", "none", 130},
    {"queenbee", "蜜蜂女王", "Rimskii Korsakov", "none", 142},
    {"chuok", "如果记忆", "何劝", "none", 74},
    {"finalfriend", "通过一个朋友 feat. Lyn", "Moh Denebi", "none", 98},
    {"tattoo", "纹身", "辣铰券", "none", 66},
    {"pitapat", "心悸(PIT-A-PAT)", "冠芒泅", "none", 105},
    {"loveisone", "一个爱..", "炔技霖", "none", 65},
    {"yuyoung", "游泳", "Jeppet", "none", 105},
    {"yegam", "预感", "剧康绕", "none", 124},
    {"hexad", "HEXAD", "Electronic Boutique", "none", 135},
    {"darkness", "The Prince of Darkness", "M2U", "none", 160},
    {"future", "Future", "Remix Station", "none", 146},
    {"playthefuture", "Play The Future", "Urbatronic Chopsticks", "none", 128},
    {"flower", "Energy Flower 3008", "r300k", "none", 133},
    {"hyper", "Hyper Magic", "Memme", "none", 170},
    {"@beyond", "Back of Beyond", "M2U", "none", 120},
    {"@blackbird", "Blackbird", "M2U", "none", 116},
    {"@gray", "Gray Street", "M2U", "none", 135},
    {"@hunter", "Gray Hunter", "M2U", "none", 125},
    {"@paradise", "Paradise", "M2U", "none", 128},
    {"@samul", "天地开闢", "M2U", "none", 150},
    {"@shottime", "Shot Time", "M2U", "none", 128},
    {"@space", "Space Destiny", "M2U", "none", 170},
    {"@toy", "Toy War", "M2U", "none", 160},
    {"@white", "White Rose", "M2U", "none", 128},
    {"@first", "First Choice", "M2U", "none", 150},
    {"@second", "Second Choice", "M2U", "none", 150},
    {"@cadillac", "Southwest Cadillac", "Jeon Jun-kyu", "none", 95},
    {"@stay", "Stay", "Mario Bolden", "none", 125},
    {"@therhythm", "The Rhythm", "Croove", "none", 135},
    {"@aquaris", "Aquaris", "Croove", "none", 140},
    {"@combination", "Combination", "Kim Zin-kwon", "none", 115},
    {"@lielie", "Lie Lie", "ANDY LEE", "none", 125},
    {"@minus1rm", "Minus1 ~Space Mix~", "Croove", "none", 140},
    {"@panic", "Panic Strike", "Forte Escape", "none", 160},
    {"@youwere", "You were the one", "Kim Min", "none", 110},
    {"@sinus", "Sinus", "Yak won", "none", 124},
    {"@envy", "Envy Mask", "Creatune", "none", 118},
    {"@iwantyou", "I Want You", "Lin-G", "none", 140},
    {"@stay", "Stay (TAK Remix)", "Mario Bolden", "none", 125},
    {"@3week", "For 3 Weeks", "Lee so eum", "none", 117},
    {"@lom", "Legend of Moonlight", "Memme", "none", 160},
    {"@sosfull", "Son of Sun (Full)", "Hosoe Shinji", "none", 200},
    {"@exist", "Exist", "Mario Bolden", "none", 114},
    {"@freedom", "Freedom", "Ruby Tuesday", "none", 93},
    {"@showdown", "Showdown", "ANDY LEE", "none", 130},
    {"@200e", " 20000000000 ", "Croove", "none", 174},
    {"@blue", "Blue", "xxdbxx", "none", 153},
    {"@qfactor", "Q Factor", "Forte Escape", "none", 130},
    {"@firstkiss", "First Kiss", "BJJ", "none", 107},
    {"@y", "Y", "ND Lee", "none", 130},
    {"@rdm", "RDM", "Andy Lee", "none", 110},
    {"@round3", "Round 3", "r300k", "none", 155},
    {"@catchtheflow", "Catch the Flow", "Creatune", "none", 97},
    {"@weluvmusic", "We Luv Music", "Junkyu Jyun", "none", 139},
    {"@climax", "Climax", "ND Lee", "none", 140},
    {"@lucid", "Lucid", "Yak won", "none", 175},
    {"@ladymade", "Ladymade Star", "ESTi", "none", 136},
    {"@syriana", "Syriana", "Bexter", "none", 135},
    {"@ghost", "幽灵(Ghost)", "STi", "none", 125},
    {"@supersonicrmx", "Super Sonic", "MR.Funky", "none", 130},
    {"@kungfu", "Kungfu Rider", "r300k", "none", 136},
    {"@night", "Night Madness", "JoyRock", "none", 160},
    {"@cheoum", "万事开头难", "015B", "none", 140},
    {"@lovemode", "Love Mode", "Clazziquai", "none", 120},
    {"@memoirs", "Memoirs", "M2U", "none", 140},
    {"@stranger", "Stranger", "LHOU", "none", 130},
    {"@hamsin", "Hamsin", "Makou", "none", 150},
    {"@lagrand", "La grand Bleu", "KIEN", "none", 165},
    {"nbranger2", "NB Rangers: Returns", "NieN", "none", 145},
    {"@ootb", "OUT OF THE BLUE", "yak won", "none", 170},
    {"oblivion1", "Oblivion(Rockin` Night Style)", "ESTi", "none", 141},
    {"@fate", "FATE", "STi", "none", 110},
    {"@tempus", "Tempus Praeterita", "Ira", "none", 145},
    {"@xeus", "Xeus", "Xeon", "none", 148},
};

static const int DJMAX_SONG_COUNT = 277;
