#pragma once
#include <string>
#include <unordered_map>

// Auto-generated IIDX song database from music_data.bin

struct IIDXSongInfo {
    std::string title;
    std::string artist;
};

inline std::unordered_map<int, IIDXSongInfo> getIIDXSongDB() {
    return {
        {1000, {"5.1.1.", "dj nagureo"}},
        {1001, {"GRADIUSIC CYBER", "TAKA"}},
        {1003, {"R3", "tiger YAMATO"}},
        {1004, {"Macho Gang", "ANAL SPYDER"}},
        {1005, {"THE EARTH LIGHT", "L.E.D. LIGHT"}},
        {1006, {"GAMBOL", "SLAKE"}},
        {1007, {"gentle stress", "DJ Swan"}},
        {1008, {"GENOM SCREAMS", "L.E.D. LIGHT"}},
        {1009, {"22DUNK", "SLAKE"}},
        {1010, {"Dr.LOVE", "baby weapon  feat.Asuka.M"}},
        {1015, {"deep in you", "dj nagureo"}},
        {1017, {"RUGGED ASH", "SYMPHONIC DEFOGGERS"}},
        {1019, {"KEEP ON MOVIN'", "N.M.R."}},
        {1020, {"PARANOIA MAX～DIRTY MIX～", "190"}},
        {2000, {".59", "dj TAKA"}},
        {2003, {"Digital MinD(A/T Libra mix)", "TaQ"}},
        {2005, {"Electro Tuned(the SubS mix)", "TaQ"}},
        {2006, {"I Was The One", "good-cool"}},
        {2008, {"Indigo Vision(full flavour hide around mix)", "TaQ"}},
        {2012, {"SP-TRIP MACHINE(for beatmania II)", "dj TAKA feat. DE-SIRE"}},
        {2016, {"PUT YOUR FAITH IN ME(for beatmania II)", "dj TAKA feat. UZI-LAY"}},
        {3000, {"CAN'T STOP FALLIN'IN LOVE", "NAOKI"}},
        {3001, {"Don't Stop!", "dj TAKA feat. JP Miles"}},
        {3004, {"era (nostalmix)", "TaQ"}},
        {3005, {"Holic", "TaQ"}},
        {3006, {"LEADING CYBER", "dj TAKA"}},
        {3007, {"Presto", "Osamu Kubota"}},
        {3008, {"R5", "tigerYAMATO with ultrabeatbox"}},
        {3009, {"REINCARNATION", "dj TAKA"}},
        {3010, {"Schlagwerk", "TaQ"}},
        {3011, {"Skyscraper", "good-cool"}},
        {3012, {"Tangerine Stream", "dj TAKA"}},
        {3013, {"THE SAFARI", "Lion Musashi"}},
        {4000, {"250bpm", "AKIRA YAMAOKA"}},
        {4001, {"ABSOLUTE", "dj TAKA"}},
        {4002, {"B4U", "NAOKI"}},
        {4003, {"Broken My Heart", "NAOKI feat.PAULA TERRY"}},
        {4004, {"CHECKING YOU OUT", "good-cool feat. JP Miles"}},
        {4005, {"Clione", "kors k"}},
        {4006, {"DXY!", "TaQ"}},
        {4007, {"empathy", "TaQ"}},
        {4008, {"era (step mix)", "TaQ"}},
        {4012, {"HIGHER", "NM feat. Sunny"}},
        {4014, {"KAMIKAZE", "dj nagureo"}},
        {4015, {"LOVE WILL・・・", "riewo"}},
        {4016, {"minimalian", "DETROIAN"}},
        {4017, {"Mr.T.(take me higher)", "Risky Men  feat.Asuka-M"}},
        {4020, {"starmine", "Ryu☆"}},
        {4021, {"Voltage (feat. Hidemaru)", "TaQ"}},
        {4023, {"Hitch Hiker2", "good-cool"}},
        {4025, {"SWEET LAB", "DJ SIMON"}},
        {4029, {"Burnin' The Floor", "NAOKI"}},
        {4032, {"FLOWERS for ALBION", "dj TAKA"}},
        {4033, {"Jam&Marmalade", "FinalOffset"}},
        {5000, {"Abyss", "dj TAKA"}},
        {5004, {"in my eyes", "ric"}},
        {5007, {"outer wall", "sampling masters MEGA"}},
        {5009, {"QQQ", "TaQ"}},
        {5010, {"Radical Faith", "TaQ"}},
        {5011, {"Real", "Aya"}},
        {5012, {"Regulus", "DJ.W"}},
        {5014, {"RIDE ON THE LIGHT (HI GREAT MIX)", "Mr.T"}},
        {5015, {"RISLIM", "ric"}},
        {5016, {"Spin the disc", "good-cool"}},
        {5017, {"STILL IN MY HEART", "NAOKI"}},
        {5018, {"still my words", "TaQ feat. Meg"}},
        {5019, {"sync", "OutPhase (TaQ/dj TAKA)"}},
        {5021, {"V", "TAKA"}},
        {5023, {"sometime", "Aya"}},
        {5024, {"THE CUBE", "DJ SUWAMI"}},
        {5025, {"LOVE AGAIN TONIGHT～for Mellisa mix～", "NAOKI feat.PAULA TERRY"}},
        {5030, {"THE SHINING POLARIS", "L.E.D. feat. Sana"}},
        {6001, {"BALLAD FOR YOU～想いの雨～", "NM feat.Thomas Howard"}},
        {6003, {"Blueberry Stream", "dj TAKA"}},
        {6004, {"Buffalo", "good-cool feat. Hideo Suwa"}},
        {6005, {"Colors (radio edit)", "dj TAKA"}},
        {6007, {"DIVE ～INTO YOUR HEART～", "NAOKI feat.PAULA TERRY"}},
        {6010, {"fly through the night", "Mr.T"}},
        {6011, {"Free Style", "Shapes"}},
        {6012, {"Frozen Ray (original mix)", "dj TAKA"}},
        {6013, {"G2", "Aya"}},
        {6014, {"L'amour et la liberté", "NAOKI underground"}},
        {6015, {"Linus", "LEGO STUDIO"}},
        {6016, {"NEMESIS", "D.J.SETUP"}},
        {6018, {"rottel-da-sun", "sampling masters MEGA"}},
        {6019, {"route 80s", "sampling masters MEGA"}},
        {6021, {"Summer Vacation(CU mix)", "OutPhase"}},
        {6022, {"Take It Easy", "Aya"}},
        {6023, {"VJ ARMY", "good-cool"}},
        {6027, {"こっちを向いてよ", "vivi"}},
        {6029, {"19,November", "good-cool"}},
        {6031, {"SOMETHING WONDERFUL", "L.E.D."}},
        {7002, {"A", "D.J.Amuro"}},
        {7003, {"AVE DE RAPINA", "Shawn The Horny Master"}},
        {7004, {"Bad Routine", "D.J. Spugna"}},
        {7006, {"Burning Heat! (Full Option Mix)", "Mr.T with Motoaki.F"}},
        {7008, {"Cheer Train", "Fuzita Blender"}},
        {7010, {"D2R", "NAOKI"}},
        {7011, {"DESTINY", "NAOKI feat.Paula Terry"}},
        {7014, {"foreplay", "Osamu Kubota"}},
        {7016, {"Glorious Days", "Noria"}},
        {7018, {"Happy Wedding", "ASKA"}},
        {7021, {"Last Message", "good-cool feat. Meg"}},
        {7022, {"Let the Snow Paint Me", "Sana"}},
        {7024, {"Love Me Do", "AKIRA YAMAOKA"}},
        {7026, {"MAX 300", "Ω"}},
        {7031, {"Somebody Like You", "good-cool"}},
        {7032, {"Spica", "D.JW"}},
        {7034, {"stoic", "TaQ"}},
        {7036, {"Tomorrow Perfume", "dj TAKA"}},
        {7037, {"traces", "TaQ"}},
        {7038, {"ZERO-ONE", "Mr.T"}},
        {7039, {"革命", "dj TAKA with NAOKI"}},
        {8000, {"abstract", "TaQ"}},
        {8001, {"airflow", "Mr.T"}},
        {8003, {"ALL RIGHT", "RAM"}},
        {8004, {"Attitude", "Y&Co."}},
        {8005, {"bit mania", "AKIRA YAMAOKA"}},
        {8006, {"Blame", "good-cool feat. Jeff Coote"}},
        {8008, {"CELEBRATE NITE", "N.M.R"}},
        {8009, {"Colors -Y&Co. Eurobeat Remix-", "dj TAKA (remixed by 横田商会)"}},
        {8013, {"dual control", "Mr.T"}},
        {8017, {"Giudecca", "D.J.SETUP"}},
        {8018, {"Halfway of promise", "Yu Takami feat. Shihori Nakane"}},
        {8020, {"HYPER BOUNDARY GATE", "L.E.D.LIGHT"}},
        {8023, {"LAB", "RAM"}},
        {8024, {"LOVE IS ORANGE", "Orange Lounge"}},
        {8025, {"Luv 2 Feel Your Body", "Shoichiro Hirata"}},
        {8026, {"memories", "TAKA"}},
        {8027, {"Monkey Dance", "Y&Co."}},
        {8028, {"murmur twins", "yu_tokiwa.djw"}},
        {8029, {"MUSIC TO YOUR HEAD", "SLAKE"}},
        {8031, {"PLEASE DON'T GO", "ASLETICS"}},
        {8032, {"rainbow flyer", "dj TAKA"}},
        {8039, {"symbolic", "TaQ"}},
        {8040, {"thunder", "Lion MUSASHI"}},
        {8043, {"WAR GAME", "ASLETICS"}},
        {8044, {"World Wide Love", "MTO"}},
        {8045, {"xenon", "Mr.T"}},
        {8048, {"桜", "Reven-G"}},
        {8049, {"蒼い衝動", "NAOKI feat.YUKI"}},
        {9000, {"lower world", "D.J.SETUP"}},
        {9001, {"Silvia Drive", "dj TAKA feat.Noria"}},
        {9002, {"lights", "flare"}},
        {9003, {"fun", "Mr.T"}},
        {9006, {"MARIA (I believe... )", "NAOKI feat.PAULA TERRY"}},
        {9008, {"ADVANCE", "SLAKE"}},
        {9010, {"Cradle", "positive MA feat.akino"}},
        {9011, {"Make A Difference", "Lala Moore with CoCoRo*Co"}},
        {9012, {"moon_child", "少年ラジオ"}},
        {9015, {"ライオン好き", "AKIRA YAMAOKA"}},
        {9016, {"真夏の花・真夏の夢", "Sana"}},
        {9018, {"Golden Horn", "Osamu Kubota"}},
        {9022, {"Logic Board", "dj nagureo"}},
        {9026, {"Karma", "TaQ"}},
        {9027, {"BAD BOY BASS!! (dj Remo-con MIX)", "Y&Co."}},
        {9028, {"quasar", "OutPhase"}},
        {9029, {"ACT", "RAM"}},
        {9030, {"SNOW", "RAM"}},
        {9033, {"SWEETEST SAVAGE", "ASLETICS"}},
        {9034, {"STAR FIELD", "SADA"}},
        {9036, {"ATOMIC AGE", "SHUNZZY"}},
        {9037, {"rottel-the-Mercury", "sampling masters MEGA"}},
        {9038, {"one or eight", "sampling masters AYA"}},
        {9039, {"Really Love", "大部真由美"}},
        {9042, {"LOVE♡SHINE", "小坂りゆ"}},
        {9043, {"PARANOIA survivor MAX", "290"}},
        {9044, {"HYPER EUROBEAT (2DX style)", "NAOKI feat.PAULA TERRY"}},
        {9045, {"Sweet Sweet♡Magic", "jun"}},
        {9046, {"bag", "Reven-G"}},
        {9048, {"e-motion 2003  -romantic extra-", "e.o.s. Remixed by dj TAKA"}},
        {9051, {"Abyss -The Heavens Remix-", "dj TAKA Remixed by Ryu☆"}},
        {9052, {"Distress", "dj TAKA Remixed by TaQ"}},
        {9055, {"I Was The One (80's EUROBEAT STYLE)", "good-cool Remixed by NAOKI"}},
        {9057, {"RISLIM -Remix-", "ric Remixed by Hisashi Nawata"}},
        {9058, {"BRIGHTNESS DARKNESS", "SPARKER"}},
        {9059, {"Quickening", "dj TAKA"}},
        {10001, {"pandora", "dj TAKA feat.Tomomi"}},
        {10002, {"BABY LOVE", "Noria"}},
        {10004, {"No.13", "TAKA respect for J.S.B."}},
        {10005, {"desolation", "Mr.T"}},
        {10006, {"EXE", "Mr.T"}},
        {10009, {"SHOOTING STAR", "小坂りゆ"}},
        {10010, {"CARRY ON NIGHT (English version)", "platoniX (EURO style)"}},
        {10013, {"Boundary", "SPARKER"}},
        {10016, {"Lucy", "ELE BLOCK"}},
        {10017, {"システムロマンス", "ヒロシ＆チー子"}},
        {10018, {"SPACE FIGHT", "AKIRA YAMAOKA"}},
        {10019, {"Back Into The Light", "Sota Fujimori"}},
        {10020, {"Rise'n Beauty", "Sota feat. Cyborg Akemi"}},
        {10022, {"雪月花", "Ryu☆"}},
        {10023, {"Narcissus At Oasis", "Ryu☆"}},
        {10024, {"rainbow rainbow", "Ryu☆"}},
        {10025, {"Love Is Eternity", "kors k"}},
        {10028, {"Innocent Walls", "TaQ"}},
        {10031, {"SCORE", "DJ Remo-con"}},
        {10033, {"Daisuke", "Y&Co."}},
        {10034, {"HIGH", "RAM"}},
        {10036, {"FEEL IT", "RAM"}},
        {10038, {"ALIEN TEMPLE", "PINK PONG"}},
        {10040, {"1st Samurai", "sampling masters MEGA"}},
        {10041, {"Debtty Daddy", "sampling masters AYA"}},
        {10042, {"Feedback", "Audio Highs"}},
        {10046, {"Freezing atmosphere", "Twin AmadeuS"}},
        {10047, {"ASTRAL VOYAGE", "EeL"}},
        {10048, {"DoLL", "ＴЁЯＲＡ"}},
        {10049, {"One More Lovely", "Risk Junk"}},
        {10052, {"GHOST REVIVAL", "L.E.D."}},
        {10053, {"GRADIUS -FULL SPEED-", "Mr.T"}},
        {11001, {"BLOCKS", "SPARKER"}},
        {11002, {"BREATH", "SPARKER"}},
        {11004, {"Don't be afraid myself", "platoniX with ray.D"}},
        {11005, {"SPEEDY CAT", "Y&Co."}},
        {11007, {"太陽～T・A・I・Y・O～", "NAOKI feat.星野奏子"}},
        {11008, {"KEY", "colors"}},
        {11009, {"awakening", "AKIRA YAMAOKA"}},
        {11010, {"Sphere", "Tatsh feat. K.Nayuki"}},
        {11011, {"ＵＬＴｉＭΛＴＥ", "ＴЁЯＲＡ"}},
        {11012, {"spiral galaxy", "D.J.SETUP"}},
        {11013, {"ANDROMEDA", "Sota Fujimori"}},
        {11014, {"RESONATE 1794", "KOHTA"}},
        {11015, {"earth scape", "dj TAKA"}},
        {11018, {"Close my Eyes for Me", "D-crew feat.DENNIS GUNN(DJ Yoshitaka SCRATCHING)"}},
        {11019, {"大桟橋", "ウッチーズ"}},
        {11025, {"Wonder Bullfighter", "Twin AmadeuS"}},
        {11026, {"ピアノ協奏曲第１番”蠍火”", "virkato"}},
        {11028, {"The Hope of Tomorrow", "Sota Fujimori"}},
        {11030, {"FAKE TIME", "dj REMO-CON"}},
        {11031, {"Click Again", "dj REMO-CON"}},
        {11032, {"RED ZONE", "Tatsh&NAOKI"}},
        {11033, {"Fly Away To India", "Baby Weapon feat.KAJIL"}},
        {11034, {"Secret of Love", "D.J.SWAN"}},
        {11035, {"Be quiet", "Ryu☆"}},
        {11036, {"AGEHA", "Ryu☆"}},
        {11037, {"gigadelic", "teranoid feat.MC Natsack"}},
        {11038, {"HORIZON", "LIA"}},
        {11040, {"AA", "D.J.Amuro"}},
        {11043, {"D.A.N.C.E.!", "DJ Yoshitaka feat.星野奏子"}},
        {11050, {"NEBULA GRASPER", "L.E.D."}},
        {11051, {"Raspberry&#9825;Heart(English version)", "jun feat. PAULA TERRY"}},
        {11052, {"GENOCIDE", "dj Killer"}},
        {12000, {"double thrash", "414"}},
        {12002, {"Little Little Princess", "SHRINE 418"}},
        {12003, {"ヒマワリ", "小坂りゆ"}},
        {12004, {"冥", "Amuro vs Killer"}},
        {12005, {"MOON RACE", "ELEKTEL"}},
        {12006, {"LESSON 5", "Risk Junk feat.Erika Mochizuki"}},
        {12007, {"rage against usual", "dj TAKA feat.Gt.Shintaro"}},
        {12008, {"INAZUMA", "dj TAKA"}},
        {12009, {"HAPPY☆ANGEL", "jun with TAHIRIH"}},
        {12010, {"EDEN", "ＴЁЯＲＡ"}},
        {12011, {"CaptivAte～浄化～", "A/I"}},
        {12012, {"Catch Me", "DJ Yoshitaka feat. ERi"}},
        {12013, {"月光", "Tatsh feat. 星野奏子"}},
        {12014, {"Under the Sky", "南さやか(BeForU) with platoniX"}},
        {12015, {"Xepher", "Tatsh"}},
        {12016, {"Twelfth Style", "Tatsh&DAYBREAKERS NEXT"}},
        {12018, {"I am", "有沢みはる from BeForU"}},
        {12019, {"合体せよ！ストロングイェーガー！！ (Ryu☆ remix)", "L.E.D./Remixed by Ryu☆"}},
        {12020, {"garden", "青野りえ"}},
        {12021, {"Agnus Dei", "あさき"}},
        {12022, {"Tizona d'El Cid", "TOMOSUKE"}},
        {12023, {"EMPTY OF THE SKY", "AKIRA YAMAOKA"}},
        {12025, {"100% minimoo-G", "Sota Fujimori"}},
        {12026, {"PLASMA", "Sota Fujimori"}},
        {12027, {"in motion", "Ryu☆"}},
        {12028, {"SigSig", "kors k"}},
        {12029, {"ラクエン", "Chonan Chiharu"}},
        {12030, {"POODLE", "Y&Co."}},
        {12031, {"Pollinosis", "dj REMO-CON"}},
        {12034, {"Get'em up to R.A.V.E", "Disconation"}},
        {12036, {"alla turca con passione", "Twin AmadeuS"}},
        {12037, {"オレはビートマニア！お前は何マニア？", "DANCE☆MAN"}},
        {12038, {"We are Disっ娘よっつ打ち命", "DANCE☆MAN feat. Disっ娘"}},
        {12039, {"Don't let it go", "ウッチーズ"}},
        {12040, {"vault of heaven", "Mr.T"}},
        {12041, {"Love Magic", "D.J.SWAN"}},
        {12043, {"First Resolution", "good-cool"}},
        {12044, {"GREEN EYES", "SLAKE"}},
        {12045, {"SCREAM SQUAD", "CALF"}},
        {12046, {"mind the gap", "Osamu Kubota"}},
        {12049, {"Aurora", "Ryu☆"}},
        {12050, {"Votum stellarum", "iconoclasm"}},
        {12051, {"Pink Rose", "Kiyommy+Seiya"}},
        {12052, {"Scripted Connection⇒ N mix", "DJ MURASAME"}},
        {12053, {"Scripted Connection⇒ H mix", "DJ MURASAME"}},
        {12054, {"Scripted Connection⇒ A mix", "DJ MURASAME"}},
        {13000, {"華蝶風雪", "白虎"}},
        {13001, {"タシカナモノ", "星野奏子 with the BAND"}},
        {13002, {"The Dirty of Loudness", "Tatsh Assault X"}},
        {13003, {"D.C.fish", "DJ MURASAME"}},
        {13005, {"嘆きの樹", "金獅子"}},
        {13009, {"Bloody Tears(IIDX EDITION)", "DJ YOSHITAKA"}},
        {13010, {"CONTRACT", "朱雀"}},
        {13011, {"INFERNO", "Caldeira feat.星野奏子"}},
        {13012, {"DEEP ROAR", "NAOKI&Tatsh"}},
        {13013, {"Leaving...", "SEIYA MURAI meets “eimy”"}},
        {13014, {"ALFARSHEAR 双神威に廻る夢", "ＴЁЯＲＡ"}},
        {13015, {"Why did you go away", "jun with TAHIRIH"}},
        {13017, {"Apocalypse ～dirge of swans～", "Zektbach"}},
        {13019, {"Heavenly Sun (IIDX VERSION)", "AKIRA YAMAOKA"}},
        {13021, {"with you…", "Sota Fujimori"}},
        {13024, {"This is Love", "D-crew feat.MAKOTO"}},
        {13025, {"罠", "good-cool"}},
        {13026, {"Ganymede", "玄武"}},
        {13028, {"BALLAD THE FEATHERS", "S.S.D.FANTASICA feat.Naomi Koizumi"}},
        {13029, {"Sun Field", "mh sequence"}},
        {13031, {"DUE TOMORROW", "Mr.T"}},
        {13032, {"BOOM BOOM DISCO NIGHT", "Y&Co."}},
        {13035, {"Power of Love", "kors k feat.PSY"}},
        {13037, {"So Fabulous !!", "HHH (Ryu☆ & Dai)"}},
        {13038, {"waxing and wanding", "青龍"}},
        {13039, {"Harmony and Lovely", "Ryu☆"}},
        {13040, {"MINT", "SLAKE"}},
        {13041, {"EURO-ROMANCE", "K-MASERA"}},
        {13044, {"TYPE MARS(G-Style Mix)", "L.E.D."}},
        {13046, {"Broadbanded", "SADA"}},
        {13047, {"Double&#9825;&#9825;Loving Heart", "Tatsh feat. Junko Hirata & Sayaka Minami"}},
        {13048, {"Zenius -I- vanisher", "Tatsh"}},
        {13050, {"WISH(EUROBEAT MIX)", "DJ YOSHITAKA feat.杉村ことみ"}},
        {13051, {"tripping contact(teranoid&MC Natsack Remix)", "kors k vs teranoid"}},
        {13052, {"MOON", "dj TAKA feat.Erika Mochizuki"}},
        {13053, {"虹色", "DJ YOSHITAKA feat. G.S.C license"}},
        {13054, {"Concertino in Blue", "佐々木博史"}},
        {13055, {"カゴノトリ～弐式～", "橙色特別室"}},
        {14000, {"リグレット", "星野奏子"}},
        {14001, {"INORI", "dj TAKA feat.HAL"}},
        {14002, {"PHOTONGENIC", "L.E.D. fw.堀澤麻衣子"}},
        {14003, {"Love Again...", "Tatsh feat. Junko Hirata"}},
        {14004, {"TRANOID", "T&S seq. factory"}},
        {14005, {"Candy Galy", "Risk Junk-G"}},
        {14006, {"never…", "Kanako Hoshino with dj TAKA"}},
        {14007, {"GOLD RUSH", "DJ YOSHITAKA-G feat.Michael a la mode"}},
        {14008, {"CaptivAte～誓い～", "A/I"}},
        {14009, {"VANESSA", "朱雀"}},
        {14011, {"星をこの手に", "DJ YOSHITAKA feat.星野奏子"}},
        {14012, {"零 - ZERO -", "ＴЁЯＲＡ"}},
        {14014, {"Blind Justice ～Torn souls, Hurt Faiths ～", "Zektbach"}},
        {14015, {"Air Bell", "D-crew"}},
        {14016, {"ヨシダさん", "AKIRA YAMAOKA"}},
        {14018, {"ANDROMEDA II", "Sota Fujimori"}},
        {14019, {"Cyber Force", "Sota Fujimori feat.cyborg AKEMI"}},
        {14020, {"smile", "miru_maki.gjw"}},
        {14021, {"LASER CRUSTER", "L.E.D."}},
        {14022, {"GRID KNIGHT", "SAW WAVE SQUAD"}},
        {14023, {"CROSSROAD ～Left Story～", "jun with TAHIRIH"}},
        {14028, {"花吹雪 ～ IIDX LIMITED ～", "S.S.D.FANTASICA feat.ユッコ"}},
        {14029, {"電人、暁に斃れる。", "L.E.D.-G"}},
        {14030, {"FIRE FIRE", "StripE"}},
        {14031, {"the shadow", "kors k"}},
        {14033, {"Second Heaven", "Ryu☆"}},
        {14035, {"Sense 2007", "good-cool"}},
        {14036, {"2hot2eat", "Osamu Kubota"}},
        {14037, {"Make Me Your Own", "good-cool ft. Raj Ramayya"}},
        {14038, {"heaven above", "kors k"}},
        {14039, {"With your Smile", "Shoichiro Hirata plus Junko Hirata"}},
        {14040, {"Roulette", "Y&Co."}},
        {14044, {"op.31 叙情", "akiko"}},
        {14046, {"KAMAITACHI", "DJ TECHNORCH fw. GUHROOVY"}},
        {14047, {"METALLIC MIND", "DJ TECHNORCH fw. GUHROOVY"}},
        {14049, {"CaptivAte～裁き～", "DJ YOSHITAKA feat.A/I"}},
        {14050, {"High School Love", "DJ YOSHITAKA feat.DWP"}},
        {14051, {"The Smile of You", "猫叉Master feat.JESSY"}},
        {14052, {"Fascination MAXX", "100-200-400"}},
        {14053, {"snow storm", "dj TAKA"}},
        {14055, {"four-leaf", "Sis Bond Chit"}},
        {14056, {"クルクル☆ラブ～Opioid Peptide MIX～", "イオンチャンネル"}},
        {14058, {"Watch out!!", "MAD Sequence*"}},
        {15000, {"Anisakis -somatic mutation type\"Forza\"-", "朱雀"}},
        {15001, {"MENDES", "Humanoid"}},
        {15002, {"Darling my LUV", "DJ Yoshitaka feat.B-Agents"}},
        {15003, {"MAX LOVE", "DJ YOSHITAKA feat.星野奏子"}},
        {15004, {"Blue Rain", "dj TAKA VS Ryu☆"}},
        {15005, {"four pieces of heaven", "Lion"}},
        {15006, {"走馬灯 -The Last Song-", "TAKA"}},
        {15007, {"THE DEEP STRIKER", "L.E.D.-G"}},
        {15008, {"STEEL NEEDLE", "Scorpion"}},
        {15009, {"SOUND OF GIALLARHORN", "L.E.D.-G"}},
        {15010, {"REMINISCENCE", "jun with Alison"}},
        {15011, {"PROMISE FOR LIFE", "ＴЁЯＲＡ WORKS"}},
        {15012, {"高高度降下低高度開傘", "Dr.Honda"}},
        {15013, {"oratio", "蓑舞衆"}},
        {15014, {"Ristaccia", "Zektbach"}},
        {15015, {"NEW GENERATION -もう、お前しか見えない-", "SUPER STAR 満-MITSURU-"}},
        {15016, {"TROOPERS", "Des-TRACT"}},
        {15018, {"マチ子の唄", "AKIRA YAMAOKA"}},
        {15019, {"beatonic nation", "Sota Fujimori"}},
        {15020, {"State Of The Art", "Sota Fujimori feat. cyborg AKEMI"}},
        {15021, {"end of world", "猫叉Master+"}},
        {15023, {"ICARUS", "Eagle"}},
        {15024, {"Dazzlin' Darlin", "HHH"}},
        {15025, {"Do it!! Do it!!", "Kraken"}},
        {15026, {"Time to Air", "青龍"}},
        {15027, {"avant-guerre", "Osamu Kubota"}},
        {15028, {"Digitank System", "DJ Mass MAD Izm*"}},
        {15029, {"エコ爺", "Y&Co."}},
        {15030, {"2 tribe 4 K", "Remo-con"}},
        {15031, {"madrugada", "PINK PONG"}},
        {15032, {"MENTAL MELTDOWN", "GUHROOVY fw.TECHNORCH"}},
        {15038, {"the trigger of innocence", "Seiya Murai"}},
        {15039, {"少年A", "Remixed by 少年ラジオ"}},
        {15040, {"scar in the earth", "猫叉Master"}},
        {15041, {"Be OK", "good-cool ft. Florence"}},
        {15043, {"Kick Out 仮面", "上野圭市(aka. Babyweapon,DJ SWAMI)feat.星野奏子"}},
        {15044, {"satfinal", "RAM"}},
        {15045, {"Wanna Party?", "RAM"}},
        {15048, {"Freeway Shuffle", "dj TAKA"}},
        {15049, {"PARANOiA ～HADES～", "αTYPE-300"}},
        {15050, {"TRIP MACHINE PhoeniX", "DE-SIRE改"}},
        {15052, {"Rising in the Sun(original mix)", "kors k feat.Rie"}},
        {15054, {"華爛漫 -Flowers-", "ＴЁЯＲＡ"}},
        {15055, {"switch", "DAISUKE ASAKURA ex.ＴЁЯＲＡ"}},
        {15056, {"ミラージュ・レジデンス", "Jimmy Weckl"}},
        {15057, {"in the Sky", "Ryu☆"}},
        {15058, {"LOVELY STORM", "L.E.D.-G"}},
        {15059, {"satellite020712 from \"CODED ARMS\"", "猫叉Master"}},
        {15061, {"Übertreffen", "TAKA respect for J.S.B."}},
        {16000, {"CaptivAte2～覚醒～", "e-lma"}},
        {16001, {"翼", "小林ゆう"}},
        {16002, {"B4U(BEMANI FOR YOU MIX)", "Remixed by DJ YOSHITAKA with Michael a la mode"}},
        {16003, {"Colorful Cookie", "Lucky Vacuum"}},
        {16004, {"V2", "TAKA"}},
        {16005, {"天空脳番長危機十六連打", "D.J.SETUP"}},
        {16006, {"不沈艦CANDY", "Risk Junk"}},
        {16008, {"HYPERION", "L.E.D."}},
        {16009, {"BITTER CHOCOLATE STRIKER", "L.E.D.-G"}},
        {16010, {"Fly Above", "Sota Fujimori"}},
        {16011, {"Arabian Rave Night", "dj MAX STEROID"}},
        {16013, {"山岡晃の「クイズ！家事都合！」", "AKIRA YAMAOKA feat.喜屋武ちあき"}},
        {16014, {"Queen's Tragedy", "猫叉Master+"}},
        {16015, {"Kung-fu Empire", "飛燕流舞"}},
        {16016, {"ミッドナイト堕天使", "Dr.Honda"}},
        {16017, {"ALL MY TURN -このターンに、オレの全てを賭ける-", "SUPER STAR 満-MITSURU-"}},
        {16018, {"Marie Antoinette", "Marguerite du Pr&eacute;"}},
        {16019, {"Turii ～Panta rhei～", "Zektbach"}},
        {16020, {"卑弥呼", "朱雀 VS 玄武"}},
        {16021, {"smooooch・∀・", "kors k"}},
        {16022, {"Flash Back 90's", "kors k as disconation"}},
        {16023, {"Programmed World", "kors k as StripE"}},
        {16024, {"まほろば", "HHH+H"}},
        {16025, {"Mind Mapping", "Ryu☆"}},
        {16026, {"3y3s", "青龍"}},
        {16027, {"Monkey Dance '09", "Y&Co. Feat. DOMINO"}},
        {16028, {"Y&Co. is dead or alive", "Y&Co."}},
        {16029, {"ALL I NEED YOUR LOVE", "GUHROOVY fw. M-Project"}},
        {16030, {"NΦ CRIME", "C×F"}},
        {16031, {"naughty girl@Queen's Palace", "DJ Mass MAD Izm*"}},
        {16032, {"BRIDAL FESTIVAL !!!", "S.S.D. with ななっち"}},
        {16034, {"Punch Love♡仮面", "上野圭市(aka. Babyweapon,DJ SWAMI)feat.星野奏子"}},
        {16035, {"I'm Screaming LOVE", "Creative Life"}},
        {16036, {"鉄甲乙女-under the steel-", "Seiya Murai"}},
        {16037, {"You'll say \"Now!\"", "BLACK STAR 幸広-YUKIHIRO-"}},
        {16038, {"Secrets", "good-cool ft. CHiCO"}},
        {16039, {"ハリツヤランデヴー", "Des-MASTERS"}},
        {16040, {"neogenesis", "DM Ashura"}},
        {16041, {"THE SHINING POLARIS(kors k mix)", "Remixed by kors k"}},
        {16042, {"Bahram Attack-猫叉Master Remix-", "猫叉Master feat.JUNE"}},
        {16043, {"Cyber Force -DJ Yoshitaka Remix-", "Remixed by DJ YOSHITAKA"}},
        {16045, {"THANK YOU FOR PLAYING", "SUPER STAR 満-MITSURU-"}},
        {16047, {"thunder HOUSE NATION Remix", "Remix by Sunset In Ibiza (SII)"}},
        {16049, {"Jack", "DesQ"}},
        {16050, {"凛として咲く花の如く", "紅色リトマス"}},
        {16051, {"Go Beyond!!", "Ryu☆ Vs. Sota"}},
        {16052, {"SOLITON BEAM", "L.E.D."}},
        {16053, {"Just a Little Smile", "Sota Fujimori"}},
        {17000, {"Elisha", "DJ YOSHITAKA"}},
        {17001, {"たからもの", "セリカ＆エリカ"}},
        {17002, {"MIRACLE MEETS", "Lucky Vacuum"}},
        {17003, {"NoN-Fiction Story!", "Creative Life"}},
        {17004, {"DROP", "dj TAKA feat.Kanako Hoshino"}},
        {17005, {"Roots of my way!", "ナイア"}},
        {17006, {"G59", "怒れる金の獅子"}},
        {17007, {"DOMINION", "L.E.D.-G"}},
        {17008, {"GALGALIM", "L.E.D."}},
        {17009, {"EXUSIA", "L.E.D.-G"}},
        {17012, {"being torn the sky", "猫叉Master+ feat.JUNE"}},
        {17013, {"She is my wife", "SUPER STAR 満-MITSURU-"}},
        {17014, {"NEW SENSATION -もう、あなたしか見えない-", "SUPER HEROINE 彩香-AYAKA-"}},
        {17015, {"Raison d'&ecirc;tre～交差する宿命～", "Zektbach"}},
        {17016, {"Almagest", "Galdeira"}},
        {17017, {"ワルツ第17番 ト短調”大犬のワルツ”", "virkato"}},
        {17020, {"バビロニア", "劇団レコード"}},
        {17021, {"Last Burning", "Dirty Androids"}},
        {17022, {"Bad Maniacs", "kors k as teranoid"}},
        {17023, {"Programmed Sun", "kors k"}},
        {17024, {"D", "Eagle"}},
        {17025, {"bloomin' feeling", "Ryu☆"}},
        {17026, {"Light Shine", "Ryu☆"}},
        {17027, {"DESIRE", "M-Project fw. GUHROOVY"}},
        {17028, {"AIR RAID FROM THA UNDAGROUND", "GUHROOVY"}},
        {17032, {"Red. by Full Metal Jacket", "DJ Mass MAD Izm*"}},
        {17033, {"コスモス", "TSU-NA"}},
        {17034, {"かずあそび", "CULTVOICE by S.S.D.PRODUCTS"}},
        {17035, {"beatchic☆仮面～好き、でいさせて～", "上野圭市(transforming into Masao♡Lovely)feat.星野奏子"}},
        {17037, {"未来のプリズム", "星野奏子"}},
        {17039, {"Keep it-秋葉工房mix-", "DJ Command feat. NAGISA"}},
        {17040, {"Dazzlin' Darlin-秋葉工房mix-", "Remixed by DJ Command"}},
        {17041, {"Session 1 -Genesis-", "PRASTIK DANCEFLOOR"}},
        {17042, {"Do Back Burn", "PRASTIK DANCEFLOOR"}},
        {17043, {"Hydrogen Blueback", "MAD CHILD"}},
        {17044, {"mosaic", "Auridy"}},
        {17046, {"Empire State Glory", "Dirty Androids"}},
        {17050, {"CaptivAte～裁き～(SUBLIME TECHNO MIX)", "Remixed by DJ YOSHITAKA"}},
        {17051, {"bass 2 bass", "Ryu☆"}},
        {17052, {"IN THE NAME OF LOVE", "Y&Co.feat.Erica"}},
        {17053, {"Special One", "kors k feat. Suzuyo Miyamoto"}},
        {17054, {"Evans", "DJ YOSHITAKA"}},
        {17055, {"水上の提督(Short mix from \"幻想水滸伝V\")", "猫叉Master"}},
        {17056, {"eRAseRmOToRpHAntOM", "L.E.D.-G VS GUHROOVY"}},
        {17057, {"DAWN -THE NEXT ENDEAVOUR-", "L.E.D. fw.堀澤麻衣子"}},
        {17058, {"サヨナラ・ヘヴン", "猫叉Master"}},
        {17059, {"quell～the seventh slave～", "dj TAKA Vs. DJ YOSHITAKA"}},
        {17060, {"SOLID STATE SQUAD", "kors k Vs. L.E.D."}},
        {17061, {"GOLDEN CROSS", "dj REMO-CON VS dj TAKA"}},
        {17062, {"The Story Begins", "SADA & Sota"}},
        {17063, {"BEAUTIFUL ANGEL", "DJ SWAN"}},
        {17064, {"THE LAST STRIKER", "L.E.D."}},
        {17065, {"Sorrows", "Asako Yoshihiro"}},
        {18000, {"Stay my side", "DJ Yoshitaka feat.RINA"}},
        {18001, {"Watch Out Pt.2", "DJ Mass MAD Izm* VS.DJ Yoshitaka"}},
        {18002, {"Tropical April", "Risk Junk"}},
        {18003, {"DAYDREAMER", "ピンクターボ"}},
        {18004, {"perditus†paradisus", "iconoclasm"}},
        {18005, {"THE DOOR INTO RAINBOW", "L.E.D."}},
        {18006, {"XANADU OF TWO", "T.Kakuta With Starving Trancer + 森永真由美"}},
        {18008, {"THE BLACK KNIGHT", "L.E.D."}},
        {18009, {"PARADISE LOST", "Ryu☆ Vs. L.E.D.-G"}},
        {18010, {"Never Fade Away", "Sota Fujimori feat. dj MAX STEROID"}},
        {18011, {"おおきなこえで", "猫叉Master feat.Sana"}},
        {18012, {"Destiny Sword", "CAPACITY GATE"}},
        {18013, {"Aegis", "IT medalion"}},
        {18014, {"ZETA～素数の世界と超越者～", "Zektbach"}},
        {18015, {"旅人リラン", "XOGO BRYKK"}},
        {18017, {"Dances with Snow Fairies", "Dr.Honda"}},
        {18018, {"I FIGHT ME", "kobo feat. Marsha"}},
        {18019, {"Vermillion", "Mystic Moon"}},
        {18020, {"Programmed Life", "kors k"}},
        {18021, {"Kailua", "kors k"}},
        {18022, {"Bounce Bounce Bounce", "kors k feat.Kanata Okajima＆楽天斎"}},
        {18023, {"Mermaid girl", "Cream puff"}},
        {18024, {"passionate fate", "Ryu☆"}},
        {18025, {"Golden Palms", "Dirty Androids"}},
        {18026, {"New Castle Legions", "Dirty Androids"}},
        {18027, {"BLUST OF WIND", "Anemo=Aspel by MLREC."}},
        {18028, {"BROKEN EDEN", "MYTHOLOGIA by MLREC."}},
        {18029, {"かげぬい ～ Ver.BENIBOTAN ～", "CULTVOICE by S.S.D.PRODUCTS"}},
        {18030, {"Rock Da House", "M-Project fw. GUHROOVY"}},
        {18032, {"灼熱Beach Side Bunny", "DJ Mass MAD Izm*"}},
        {18035, {"Answer", "星野奏子"}},
        {18036, {"WISE UP!", "木之下慶行 feat.星野奏子"}},
        {18039, {"Session 9 -Chronicles-", "PRASTIK DANCEFLOOR"}},
        {18040, {"Space Time", "NISH"}},
        {18042, {"夕焼け ～Fading Day～", "JAKAZiD"}},
        {18043, {"Believe In Me", "Uraken feat. Calyn Tsukishima"}},
        {18044, {"Let The Track Flow", "Brisk & Ham"}},
        {18045, {"Energy Drive", "kevin energy"}},
        {18047, {"Breaking the ground", "Art of Fighters"}},
        {18050, {"reunion", "Tatsh"}},
        {18051, {"ANTHEM LANDING", "DJムラサメ"}},
        {18053, {"Medicine of love", "イロハ＆リリナ"}},
        {18054, {"Eternal Tears", "ツガル"}},
        {18055, {"Fantasia", "ＴЁЯＲＡ"}},
        {18056, {"SABER WING", "TAG"}},
        {18057, {"DM STAR～関西 energy style～", "NAOKI"}},
        {18059, {"ALBIDA", "DJ YOSHITAKA"}},
        {18060, {"黒髪乱れし修羅となりて", "村正クオリア"}},
        {18061, {"sakura storm", "Ryu☆"}},
        {18062, {"Everlasting Resort", "SUPER STAR 満-MITSURU-"}},
        {18064, {"STELLAR WIND", "L.E.D."}},
        {18066, {"Sakura Reflection", "Ryu☆"}},
        {18067, {"THE FALLEN", "L.E.D.-G"}},
        {18068, {"Broken", "dj TAKA feat.AiMEE"}},
        {18069, {"Wuv U", "kors k"}},
        {18071, {"SPECIAL SUMMER CAMPAIGN!", "Lucky Vacuum"}},
        {18072, {"中華急行", "Ryu☆"}},
        {19001, {"Snake Stick", "DJ Yoshitaka VS. DJ Mass MAD Izm*"}},
        {19002, {"天空の夜明け", "Cuvelia"}},
        {19003, {"F", "D.J.Amuro"}},
        {19004, {"In the Blackest Den", "Bulluvegola"}},
        {19005, {"恋する☆宇宙戦争っ！！", "Prim"}},
        {19006, {"ANAGRAMS I to Y", "Mayumi Morinaga"}},
        {19007, {"YAKSHA", "Neulakyussra"}},
        {19008, {"DIAVOLO", "度胸兄弟"}},
        {19009, {"Scharfrichter", "Ashemu"}},
        {19010, {"Lucky Days", "Sota Fujimori feat. Kanako Hoshino"}},
        {19011, {"CALL", "猫叉Master"}},
        {19013, {"Several Words", "CAPACITY GATE"}},
        {19014, {"SA.YO.NA.RA. SUPER STAR", "SUPER STAR 満-MITSURU-"}},
        {19015, {"蛇神", "Zektbach"}},
        {19016, {"Todestrieb", "Rche"}},
        {19017, {"GIGANT", "seiya-murai"}},
        {19018, {"prompt", "wｘs ft.*spiLa*"}},
        {19019, {"衰色小町メランコリア", "iNO"}},
        {19020, {"Quick Silver", "Mystic Moon"}},
        {19022, {"君のハートにロックオン", "Dr.Honda"}},
        {19024, {"Almace", "Qrispy Joybox"}},
        {19025, {"Drive Me Crazy", "kors k feat.古川未鈴"}},
        {19026, {"The Sampling Paradise", "Mamonis"}},
        {19027, {"Release The Music", "kors k"}},
        {19028, {"Thunderbolt", "雷龍"}},
        {19029, {"Follow Tomorrow", "HHH×MM×ST"}},
        {19030, {"NNRT", "Levaslater"}},
        {19031, {"SHADE", "DJ MURASAME vs dj Killer"}},
        {19032, {"24th Century BOY", "Tatsh"}},
        {19033, {"The Limbo", "STN"}},
        {19034, {"Miami Sunset Drive", "Dirty Androids"}},
        {19035, {"A MINSTREL ～ ver. short-scape ～", "KANTASIA by S.S.D. PRODUCTS"}},
        {19036, {"LAX5 feat.Ryota Yoshinari", "Katana Sounds"}},
        {19037, {"BLACK.by X-Cross Fade", "DJ Mass MAD Izm*"}},
        {19038, {"Yellow Sunrise", "xac"}},
        {19039, {"陽炎", "星野奏子"}},
        {19040, {"Mermaid girl-秋葉工房 MIX-", "Remixed by DJ Command"}},
        {19042, {"聖人の塔", "Beridzebeth"}},
        {19045, {"Express Emotion", "REDALiCE feat. Shihori"}},
        {19046, {"突撃!ガラスのニーソ姫!", "山本椛 (monotone)"}},
        {19047, {"Liquid Crystal Girl feat. echo", "kmp"}},
        {19048, {"Round and Round", "Masayoshi Minoshima feat. 綾倉盟"}},
        {19049, {"Star Trail", "Nhato"}},
        {19050, {"LOVE B.B.B", "SWAN K feat. Asuka M"}},
        {19051, {"Voxane", "Remo-con"}},
        {19052, {"Change the World", "Tatsh feat.小田ユウ"}},
        {19053, {"ユミル", "MYTHOLOGIA by MLREC."}},
        {19054, {"Phoenix", "Hommarju"}},
        {19055, {"RESISTANCE", "セリカ"}},
        {19056, {"LETHEBOLG ～双神威に斬り咲けり～", "ＴЁЯＲＡ"}},
        {19058, {"I'm so Happy", "Ryu☆"}},
        {19059, {"Snow Goose", "Mutsuhiko Izumi"}},
        {19060, {"Far east nightbird", "猫叉Master"}},
        {19062, {"Infinite cave", "猫叉Master+"}},
        {19063, {"QUANTUM TELEPORTATION", "L.E.D."}},
        {19064, {"fffff", "Five Hammer"}},
        {19065, {"子供の落書き帳", "佐々木博史"}},
        {19067, {"yellow head joe", "S-C-U"}},
        {19068, {"WONDER WALKER", "L.E.D."}},
        {19069, {"532nm", "Ryu☆"}},
        {19070, {"ビューティフルレシート", "Lucky Vacuum"}},
        {19071, {"quaver♪", "Risk Junk"}},
        {19072, {"Castle on the Moon", "青龍"}},
        {19073, {"Flip Flap", "kors k"}},
        {19074, {"TITANS RETURN", "L.E.D."}},
        {19075, {"HAERETICUS", "D.J.Amuro Vs MAX MAXIMIZER"}},
        {20000, {"planarian", "S-C-U"}},
        {20002, {"Liberation", "dj TAKA"}},
        {20003, {"ΕΛΠΙΣ", "dj TAKA"}},
        {20004, {"狂イ咲ケ焔ノ華", "覚醒ノPrim"}},
        {20005, {"BLUE STRAGGLER", "L.E.D."}},
        {20006, {"トリカゴノ鳳凰", "L.E.D. Vs. 幽閉サテライト"}},
        {20007, {"キャトられ♥恋はモ～モク", "ギュ～っとしたい♥Prim"}},
        {20008, {"Confiserie", "L.E.D. vs S-C-U"}},
        {20009, {"POINT ZERO", "猫叉Master+"}},
        {20011, {"connective", "猫叉Master feat.*spiLa*"}},
        {20012, {"Proof of the existence", "猫叉Master+"}},
        {20013, {"Rainbow after snow", "猫叉Master feat.林ももこ"}},
        {20015, {"Re:GENERATION", "TAG feat. ERi"}},
        {20016, {"In Heaven", "Sota Fujimori"}},
        {20017, {"GRADIUS 2012", "Sota Fujimori"}},
        {20018, {"CONCEPTUAL", "Sota Fujimori 2nd Season"}},
        {20019, {"龍と少女とデコヒーレンス", "黒猫ダンジョン"}},
        {20020, {"Elemental Creation", "dj TAKA meets DJ YOSHITAKA"}},
        {20021, {"8bit Princess", "seiya-murai feat. ALT"}},
        {20022, {"下弦の月", "iNO"}},
        {20023, {"New Lights", "kors k"}},
        {20024, {"Howling", "PON"}},
        {20025, {"VEGA", "REDALiCE"}},
        {20027, {"Präludium", "Yuko Takahashi"}},
        {20028, {"rumrum triplets", "yu_tokiwa.djw"}},
        {20029, {"Thor's Hammer", "ユニバーサル度胸兄弟"}},
        {20030, {"BRAVE GLOW", "SOUND HOLIC feat. Nana Takahashi"}},
        {20031, {"Illegal Function Call", "U1-ASAMi"}},
        {20032, {"Ascalon", "Qrispy Joybox"}},
        {20033, {"I know You know", "Suke+Suke feat.Ribbon"}},
        {20035, {"S!ck", "Eagle"}},
        {20036, {"405nm (Ryu☆mix)", "Another Infinity"}},
        {20037, {"Fly you to the star", "Another Infinity feat. Mayumi Morinaga"}},
        {20038, {"Plan 8", "Ryu☆"}},
        {20039, {"仮想空間の旅人たち", "DJ MURASAME"}},
        {20040, {"Light and Cyber…", "Tatsh"}},
        {20041, {"SYNC-ANTHEM", "Tatsh feat. 星野奏子"}},
        {20043, {"Timepiece phase II (CN Ver.)", "佐々木博史"}},
        {20044, {"ラキラキ", "Mutsuhiko Izumi & S-C-U"}},
        {20046, {"Beastie Starter", "GUHROOVY"}},
        {20047, {"†渚の小悪魔ラヴリィ～レイディオ†(IIDX EDIT)", "夏色ビキニのPrim"}},
        {20048, {"Little Star", "REDALiCE feat. Ayumi Nomiya"}},
        {20049, {"アストライアの双皿", "ZODIACSYNDICATE"}},
        {20051, {"Sol Cosine Job 2", "DJ TECHNORCH"}},
        {20052, {"ILIAS", "Masayoshi Minoshima feat. 坂上なち"}},
        {20053, {"FLOWER", "DJ YOSHITAKA"}},
        {20054, {"即席！脳直★ミュージックシステム", "MOSAIC.WAV"}},
        {20055, {"カジノファイヤーことみちゃん", "ARM feat. 山本椛 + Brasscapsule"}},
        {20058, {"True Blue", "dj TAKA feat.AiMEE"}},
        {20059, {"Take My Life", "Y&Co."}},
        {20061, {"メイメツ、フラグメンツ", "中山真斗(Elements Garden)feat.桜川めぐ"}},
        {20062, {"STULTI", "MAX MAXIMIZER VS DJ TOTTO"}},
        {20063, {"Devilz Staircase", "OSTER project"}},
        {20064, {"ZED", "USAO"}},
        {20065, {"Shining World", "DJ Genki feat. Yukacco"}},
        {20066, {"Neonlights", "DJ Noriken"}},
        {20067, {"Timepiece phase II", "佐々木博史"}},
        {20068, {"LUV CAN SAVE U", "HIDEKI NAGANUMA"}},
        {20070, {"DAY DREAM", "Mutsuhiko Izumi"}},
        {20071, {"JOMANDA", "DJ YOSHITAKA"}},
        {20072, {"New Decade IIDX Edition", "Sota F."}},
        {20073, {"Hollywood Galaxy", "dj TAKA"}},
        {20074, {"neu", "少年ラジオ"}},
        {20076, {"Reflection Into the EDEN", "猫叉Master"}},
        {20082, {"Time To Empress", "dj TAKA feat.wac & secret K"}},
        {20083, {"たまゆら", "佐々木博史"}},
        {20086, {"Saturn", "Mr.Saturn"}},
        {20087, {"Cookie Bouquets", "L.E.D. vs TOMOSUKE fw.crimm"}},
        {20088, {"mnemoniq", "youhei shimizu"}},
        {20089, {"お米の美味しい炊き方、そしてお米を食べることによるその効果。", "大日本鉄倶楽部【あさき＆９６】"}},
        {20090, {"創世ノート", "PON+wac"}},
        {20091, {"Synergy For Angels", "TAG×U1-ASAMi"}},
        {20093, {"GAIA", "猫叉L.E.D.Master+"}},
        {20094, {"Zirkfied", "iconoclasm"}},
        {20095, {"examination leave", "dj razzle dazzle"}},
        {20096, {"VALLIS-NERIA", "DJ YOSHITAKA"}},
        {20097, {"Valanga", "DJ TOTTO"}},
        {20098, {"梅雪夜", "Qrispy Joybox feat.mao"}},
        {20099, {"音楽", "弁士カンタビレオ"}},
        {20100, {"朧", "HHH×MM×ST"}},
        {20101, {"シュレーディンガーの猫", "Cait Sith"}},
        {20102, {"SHION", "DJ YOSHITAKA"}},
        {21001, {"rainbow guitar weeps", "dj TAKA"}},
        {21002, {"旋律のドグマ～Misérables～", "楓璃夢＝ジークフリード＝ファイエルローゼン"}},
        {21003, {"EXTREME MACH COLLIDER", "L.E.D."}},
        {21004, {"Element of SPADA", "猫叉Master feat.霜月はるか"}},
        {21005, {"DARK LEGACY", "BaSTeT"}},
        {21006, {"牧神笛吹きて", "楽士ゾディアック"}},
        {21007, {"Critical Crystal", "青龍"}},
        {21008, {"Insane Techniques", "kors k"}},
        {21011, {"罪と罰", "Xceon feat. Mayumi Morinaga"}},
        {21012, {"Close the World feat.a☆ru", "天叢雲剣"}},
        {21013, {"Devilz Sacrifice -贖罪の羊-", "OSTER project"}},
        {21014, {"MAGIC & LOVE", "DJ Genki feat. Yukacco"}},
        {21015, {"Miracle 5ympho X", "USAO"}},
        {21016, {"Elektrick U-Phoria", "DJ Noriken"}},
        {21018, {"Overload Frontier", "DJ Shimamura"}},
        {21019, {"Adularia", "DJ TOTTO"}},
        {21020, {"Valgus", "DJ Myosuke feat.Yukacco"}},
        {21021, {"Odin", "Noizenecio"}},
        {21022, {"MAD ATTACK", "HALFBY"}},
        {21024, {"Funny shuffle", "猫叉Master+"}},
        {21025, {"NPC World", "PON"}},
        {21026, {"Lighting Shower", "TAG"}},
        {21027, {"m1dy Deluxe", "m1dy"}},
        {21030, {"超!!遠距離らぶ♡メ～ル", "ななひら"}},
        {21032, {"煉獄のエルフェリア", "猫叉Master+"}},
        {21033, {"INSOMNIA", "ジャカルタファンクブラザーズ"}},
        {21034, {"Wonder Girl feat. Kanae Asaba", "Y&Co."}},
        {21035, {"RISE", "Dirty Androids"}},
        {21037, {"ALBA -黎明-", "SOUND HOLIC feat. Nana Takahashi"}},
        {21038, {"お願いアインシュタイン", "中山真斗 feat.桜川めぐ"}},
        {21039, {"into the battlefield", "the wandering bard"}},
        {21041, {"diagram", "Expander"}},
        {21042, {"refractive index", "Sota Fujimori"}},
        {21043, {"Hypersonik", "Eagle"}},
        {21044, {"BLUE DRAGON(雷龍RemixIIDX)", "青龍"}},
        {21045, {"Last Dance", "dj TAKA"}},
        {21047, {"ra'am", "雷龍"}},
        {21048, {"疾風迅雷", "KUMOKIRI"}},
        {21050, {"Verflucht", "Tyrfing"}},
        {21051, {"BRAVE OUT", "nomico / DOWNFORCE"}},
        {21052, {"Feel The Beat", "Falsion"}},
        {21053, {"Pharaoh", "劇団レコード"}},
        {21055, {"Idola", "iconoclasm feat.GUMI"}},
        {21056, {"I will be back -オレは帰ってきた-", "SUPER STAR 満-MITSURU-"}},
        {21058, {"アルストロメリア", "TAG"}},
        {21059, {"Sigmund", "Gram"}},
        {21060, {"ÆTHER", "TAG underground"}},
        {21061, {"M.D.Injection", "Project B-"}},
        {21062, {"VOX UP", "sampling masters MEGA vs 青龍"}},
        {21063, {"BRAINSTORM", "Hardcore United Tokyo(teranoid & DJ TECHNORCH)"}},
        {21064, {"Recollection", "Noria"}},
        {21065, {"Claiomh Solais", "DJ Yoshitaka VS S.S.D."}},
        {21066, {"Unicorn tail", "DJ YOSHITAKA"}},
        {21067, {"RIZING YOU UP", "Ryu☆"}},
        {21068, {"THE DETONATOR", "teranoid VS L.E.D.-G"}},
        {21069, {"Ancient Scapes", "Durandal"}},
        {21073, {"invoker", "Caladborg"}},
        {21076, {"PUNISHER", "TAG×PON"}},
        {21077, {"HYENA", "Hommarju"}},
        {21078, {"Squeeze", "VENUS feat. Mutsuhiko Izumi"}},
        {21079, {"デッドボヲルdeホームラン", "猫叉Masterβ2"}},
        {21081, {"轟け！恋のビーンボール！！", "ダイナミック野球兄弟 v.s. クロスファイヤーPrim"}},
        {21082, {"IX", "dj TAKA VS DJ TOTTO feat.藍"}},
        {21083, {"Engraved Mark", "Ryu☆ ∞ Des-ROW"}},
        {21084, {"バンブーソード・ガール", "cosMo＠暴走P"}},
        {21085, {"Cleopatrysm", "ピラミッ℃"}},
        {21087, {"KHAMEN BREAK", "くふおー"}},
        {21088, {"海神", "兎々"}},
        {21089, {"KAISER PHOENIX", "96"}},
        {21090, {"SCHWARZSCHILD FIELD", "L.E.D."}},
        {22001, {"Broken Sword", "金獅子 VS 麒麟"}},
        {22002, {"Line 4 Ruin", "Ryu☆"}},
        {22003, {"Rave*it!! Rave*it!!", "機龍"}},
        {22004, {"Shooting Fireball", "dj TAKA"}},
        {22005, {"Say YEEEAHH", "kors k"}},
        {22006, {"Cosmic Cat", "8bit Moonside"}},
        {22007, {"Reflux", "Eagle"}},
        {22008, {"CHRONO DIVER -NORNIR-", "L.E.D."}},
        {22009, {"表裏一体！？怪盗いいんちょの悩み♥", "◇◆噂の怪盗少女 ぷらずま★彡Prim◇◆"}},
        {22010, {"もっと！モット！ときめき feat. 松下", "シャイニング度胸兄弟"}},
        {22011, {"NEO GENERATOR SEVEN", "L.E.D.-G"}},
        {22012, {"共鳴遊戯の華", "アイテール魔導士隊"}},
        {22013, {"chrono diver -fragment-", "猫叉Master feat.三澤 秋"}},
        {22014, {"AFRO KNUCKLE", "猫叉Master+"}},
        {22015, {"Despair of ELFERIA", "猫叉Master"}},
        {22016, {"Flashes", "Dollscythe"}},
        {22017, {"Symmetry", "猫叉Master"}},
        {22018, {"FANTASTIC THREE", "ジャカルタファンクブラザーズ"}},
        {22019, {"illuminate", "Sota Fujimori"}},
        {22024, {"恋は白帯、サンシロー", "星野奏子"}},
        {22025, {"Chain of pain", "kors k VS 猫叉Master+"}},
        {22026, {"白露の風", "Qrispy Joybox feat. 常盤ゆう"}},
        {22027, {"Beat Radiance", "iNO"}},
        {22028, {"GUILTY", "D.J.SETUP"}},
        {22029, {"COLOSSEUM", "劇団レコード"}},
        {22031, {"超青少年ノ為ノ超多幸ナ超古典的超舞曲", "Project B-"}},
        {22032, {"リリーゼと炎龍レーヴァテイン", "黒猫ダンジョン"}},
        {22033, {"cinder", "PHQUASE"}},
        {22034, {"Realize Maze", "movies (moimoi×Xceon×Dai.)"}},
        {22035, {"Ｘ↑Ｘ↓", "DJ TECHNORCH"}},
        {22037, {"十六夜セツナ", "Xceon feat.Mayumi Morinaga"}},
        {22038, {"紅牡丹", "DJ NAGAI feat. a☆ru"}},
        {22039, {"BLUE MIRAGE", "DJ CHUCKY"}},
        {22040, {"#The_Relentless", "DJ Noriken"}},
        {22041, {"Blaze it UP!", "DJ Shimamura"}},
        {22042, {"Sweet Radar", "DJ Genki feat. Yukacco"}},
        {22043, {"IMPLANTATION", "TOMOSUKE"}},
        {22044, {"Night sky", "USAO"}},
        {22046, {"SAMSARA", "SOUND HOLIC feat. Nana Takahashi"}},
        {22047, {"時空トラベローグ", "SWING HOLIC feat. A～YA"}},
        {22048, {"ぷろぐれっしぶ時空少女！うらしまたろ子ちゃん！", "ARM(IOSYS) feat. 山本椛"}},
        {22049, {"HELL SCAPER -Last Escape Remix-", "Remixed by DJ TECHNORCH fw.GUHROOVY"}},
        {22052, {"IXION", "L.E.D."}},
        {22053, {"Gravigazer", "DJ TOTTO"}},
        {22054, {"Chrono Diver -PENDULUMs-", "猫叉L.E.D.Master+"}},
        {22055, {"SpaceLand☆TOYBOX", "OSTER project"}},
        {22056, {"TA・DA ☆ YO・SHI", "Y&Co."}},
        {22057, {"Vulkan", "Hommarju"}},
        {22058, {"Scars of FAUNA", "猫叉Master"}},
        {22059, {"ベィスドロップ・フリークス", "かめりあ feat. ななひら"}},
        {22060, {"Sakura Mirage", "Ryu☆"}},
        {22061, {"Hello Happiness", "P*Light feat. mow*2"}},
        {22062, {"打打打打打打打打打打", "ヒゲドライバー join. SELEN"}},
        {22063, {"No Tears", "RoughSketch feat.Aikapin"}},
        {22064, {"鬼天", "兎々"}},
        {22065, {"entelecheia", "Rche"}},
        {22067, {"とろぴかる倶楽部", "HALFBY"}},
        {22068, {"Beyond The Earth", "猫叉Master"}},
        {22069, {"The Least 100sec", "Sasaki Hirofumi"}},
        {22070, {"fallen leaves -IIDX edition-", "猫叉Master"}},
        {22073, {"Monopole.", "cosMo＠暴走P"}},
        {22074, {"TOXIC VIBRATION", "SOUND HOLIC Vs. T.Kakuta feat. YURiCa"}},
        {22075, {"Erosion Mark", "kors k REASM Des-ROW"}},
        {22077, {"ZZ", "D.J.Amuro"}},
        {22079, {"TIEFSEE", "SOUND HOLIC Vs. dj TAKA feat. YURiCa"}},
        {22080, {"We're so Happy (P*Light Remix) IIDX ver.", "Remixed by P*Light"}},
        {22083, {"千年ノ理", "猫叉Master"}},
        {22084, {"妖隠し -あやかしかくし-", "DJ TOTTO feat.3L"}},
        {22085, {"取り残された美術(Arranged:HiZuMi)", "幽閉サテライト feat. senya"}},
        {22086, {"Scarlet Moon", "REDALiCE feat. Ayumi Nomiya"}},
        {22087, {"それは花火のような恋", "夏色バーニングラブ☆Prim"}},
        {22088, {"パ→ピ→プ→Yeah!", "ヒゲドライバー join. shully & Nimo"}},
        {22089, {"EBONY & IVORY", "OSTER project"}},
        {22090, {"In The Breeze", "96 & Sota ft. Mayumi Morinaga"}},
        {22091, {"Sounds Of Summer", "Hommarju"}},
        {22092, {"Chronos", "TAG"}},
        {22093, {"少年は空を辿る", "Power Of Nature"}},
        {22094, {"ドッキン☆サマーあばんちゅーる", "L.E.D.-G + Qrispy Joybox + ARM feat. ななひら"}},
        {22095, {"夏色DIARY - L.E.D.-G STYLE MIX -", "猫叉王子 feat.L.E.D.-G"}},
        {22098, {"Discloze", "lapix"}},
        {22099, {"Invitation from Mr.C", "C-Show"}},
        {22100, {"PENDUAL TALISMAN", "猫叉L.E.D.Master"}},
        {23000, {"DIAMOND CROSSING", "S-C-U vs L.E.D."}},
        {23001, {"駅猫のワルツ", "ミニョンヌ鉄道兄弟"}},
        {23002, {"SHELTER OF THE MIND", "YURiCa/花たん"}},
        {23003, {"か・し・ま・し☆PUMP UP！", "miko"}},
        {23004, {"ギョギョっと人魚 爆婚ブライダル", "海の底からマーメイド Prim by ARM×狐夢想"}},
        {23005, {"Nightmare before oversleep", "猫叉Master"}},
        {23007, {"Highcharge Divolt", "HuΣeR"}},
        {23008, {"Uh-Oh", "kors k"}},
        {23009, {"M4K3 1T B0UNC3", "kors k"}},
        {23010, {"Donkey Donk", "Ryu☆"}},
        {23011, {"Everlasting Last", "HHH×MM×ST"}},
        {23012, {"オルタネイトβ", "Xceon feat. Mayumi Morinaga"}},
        {23013, {"refrain", "dj TAKA feat.AiMEE"}},
        {23015, {"Central Station", "Recycle"}},
        {23016, {"少女アリスと箱庭幻想コンチェルト", "DJ TOTTO"}},
        {23017, {"Outbreak", "USAO"}},
        {23018, {"X", "D.J.Amuro"}},
        {23019, {"セロトニン", "U1 overground"}},
        {23021, {"Daily Lunch Special", "Lucky Vacuum"}},
        {23022, {"明鏡止水", "TOMOSUKE feat. あさき"}},
        {23026, {"Go Faraway", "DJ Noriken feat. Yukacco"}},
        {23027, {"Dynamite", "USAO"}},
        {23028, {"Aublia", "onoken feat. ALIAKE"}},
        {23029, {"Musik LoverZ", "RoughSketch"}},
        {23030, {"Routing", "かめりあ"}},
        {23031, {"STARLIGHT DANCEHALL", "P*Light"}},
        {23032, {"追想快晴テーマパーク", "PHQUASE"}},
        {23033, {"Set U Free feat. Kanae Asaba", "Y&Co."}},
        {23034, {"SURVIVOR", "SOUND HOLIC Vs. ZYTOKINE feat. Nana Takahashi"}},
        {23035, {"星屑ディスタンシア", "ARM feat. 普透明度 + Brasscapsule"}},
        {23036, {"NANAIRO", "LIQU@。"}},
        {23037, {"AO-1", "電龍"}},
        {23038, {"Nowhere", "Nhato"}},
        {23039, {"do the thing feat. Kanae Asaba", "MK"}},
        {23041, {"真 地獄超特急 -HELL or HELL-", "DJ TECHNORCH Vs. L.E.D.Light-G"}},
        {23043, {"Rock It", "Hommarju"}},
        {23044, {"Violet Rose", "OSTER project"}},
        {23045, {"めいさいアイドル☆あいむちゃん♪", "DJ SHARPNEL feat. みらい"}},
        {23046, {"量子の海のリントヴルム", "黒猫ダンジョン"}},
        {23047, {"シュッパツシンコウ・シサカンコ", "星野奏子"}},
        {23048, {"麗 ～うらら～", "SOUND HOLIC feat. Nana Takahashi"}},
        {23049, {"NO LIMIT -オレ達に限界は無い-", "SUPER STAR 満-MITSURU- vs. 伝説のダンサー マイク"}},
        {23050, {"朝焼けから始まるボクらの小さな旅", "cosMo＠暴走P"}},
        {23051, {"灼熱 Pt.2 Long Train Running", "DJ Mass MAD Izm*"}},
        {23052, {"Inner Spirit", "lapix"}},
        {23053, {"On the FM", "C-Show"}},
        {23054, {"Damage Per Second", "Maozon"}},
        {23055, {"199024club -Re:BounceKiller-", "DJ Mass MAD Izm*"}},
        {23056, {"Arcana", "Maozon"}},
        {23057, {"Acid Pumper", "ni-21"}},
        {23058, {"Exchange Place", "Dirty Androids"}},
        {23060, {"quick master (reform version)", "youhei shimizu"}},
        {23061, {"Devil's Gear", "DJ Myosuke"}},
        {23062, {"Tori-no-kimochi", "猫叉Master+"}},
        {23063, {"Blue Spring Express", "DJ Scratch & Bend"}},
        {23066, {"GOBBLE", "Kimitaka Matsumae"}},
        {23067, {"GENERATE feat.綾倉盟", "Masayoshi Minoshima"}},
        {23068, {"chaos eater -IIDX edition-", "猫叉Master+"}},
        {23069, {"Battle Train -IIDX Edition-", "Sota Fujimori"}},
        {23070, {"Welcome", "Uraken"}},
        {23072, {"Konzert V", "Remo-con vs. dj TAKA"}},
        {23073, {"Derelict Star feat. Ryu*", "Remo-con"}},
        {23074, {"POSSESSION", "TAG underground"}},
        {23075, {"Godspeed", "dj TAKA xxx 猫叉Master xxx L.E.D."}},
        {23076, {"La dolce primavera", "OSTER project"}},
        {23079, {"NINJA IS DEAD IIDX ver.", "P*Light"}},
        {23080, {"Violet Pulse", "G.K"}},
        {23082, {"STARLiGHT", "星龍"}},
        {23083, {"紫陽花 -AZISAI-", "Camellia Vs. Expander"}},
        {23084, {"Journey", "猫叉Master"}},
        {23085, {"CODE:1 [revision1.0.1]", "HEXA"}},
        {23087, {"Super Duper Racers", "kors k & Numb'n'dub"}},
        {23088, {"NZM", "The 4th"}},
        {23090, {"Grand Chariot", "xi"}},
        {23091, {"Sephirot", "SHIKI"}},
        {23092, {"StrayedCatz", "削除"}},
        {23093, {"Angelic Jelly", "t+pazolite"}},
        {23094, {"Triple Counter", "DJ YOSHITAKA meets dj TAKA"}},
        {23095, {"ZEPHYRANTHES", "TAG"}},
        {24000, {"鴉", "L.E.D.-G"}},
        {24001, {"焔極OVERKILL", "RoughSketch Vs. L.E.D.-G"}},
        {24003, {"イザナミノナゲキ", "猫叉Master"}},
        {24004, {"AsiaN distractive", "猫叉劇団"}},
        {24005, {"Super Rush", "kors k"}},
        {24006, {"Rave Cannon", "kors k"}},
        {24007, {"Caterpillar", "Eagle"}},
        {24008, {"¡Viva!", "Ryu*"}},
        {24009, {"OOO", "Ryu☆ feat.moimoi"}},
        {24010, {"Mare Nectaris", "神楽"}},
        {24011, {"冬椿 ft. Kanae Asaba", "Xceon"}},
        {24012, {"TOGAKUSHI", "SETUP"}},
        {24013, {"SINOBUZ Fantasy", "Noria"}},
        {24014, {"津軽雪", "罠師 VS 安室"}},
        {24015, {"Modular Technology", "Sota Fujimori"}},
        {24016, {"Honey Trap", "Expander"}},
        {24017, {"ROTTERDAM SHOGUN", "ABDI from ジャカルタファンクブラザーズ"}},
        {24018, {"DORNWALD ～Junge～", "DJ TOTTO"}},
        {24019, {"獅子霞麗ノ舞", "HuΣeR"}},
        {24020, {"ECHIDNA", "HuΣeR"}},
        {24021, {"Quakes", "dj Hellix"}},
        {24022, {"PAPAYAPA BASS", "かめりあ feat. ななひら"}},
        {24023, {"焱影", "RoughSkreamZ feat.楽天斎"}},
        {24024, {"SAY BAY", "P*Light"}},
        {24025, {"(This Is Not) The Angels", "Hommarju"}},
        {24026, {"Selfish Sweet", "OSTER project feat. かなたん"}},
        {24027, {"Be A Star", "PHQUASE feat.ぁゅ"}},
        {24028, {"Egret and Willow", "Dirty Androids"}},
        {24029, {"禍根", "U1 overground"}},
        {24030, {"Sarutobi Champion is 拙者", "Project B-"}},
        {24031, {"次葉 -turn the page-", "小寺可南子"}},
        {24032, {"AO-∞", "青龍"}},
        {24033, {"忍恋花", "黒脛"}},
        {24034, {"Go Ahead!!", "Ryu☆ Vs. Sota"}},
        {24036, {"#MAGiCVLGiRL_TRVP_B3VTZ", "DJ Noriken"}},
        {24037, {"The Commanders", "USAO"}},
        {24038, {"Umbral", "Maozon"}},
        {24039, {"Steel Edge", "Maozon"}},
        {24040, {"Music is The Answer", "C-Show"}},
        {24041, {"Amazing Mirage", "lapix"}},
        {24043, {"XINOBIKILL", "SOUND HOLIC feat. Nana Takahashi"}},
        {24044, {"FUZIN RIZIN", "SOUND HOLIC feat. Nana Takahashi & 709sec."}},
        {24045, {"ディッシュウォッシャー◎彡おいわちゃん", "ARM×狐夢想 feat. 山本椛"}},
        {24046, {"ちらちら・はらはら", "NU-KO"}},
        {24047, {"Believe in you", "DJ Shimamura feat. Renna"}},
        {24049, {"Breakin' Chain", "REDALiCE feat. MONICO"}},
        {24050, {"GuNGNiR", "Gram"}},
        {24051, {"HADES", "Massive New Krew"}},
        {24052, {"Remedy feat. Kanae Asaba", "Y&Co."}},
        {24054, {"Beyond The Seven", "Nhato"}},
        {24055, {"elemental bender feat. Kanae Asaba", "MK"}},
        {24056, {"Seaside Labyrinth", "Dirty Androids"}},
        {24057, {"SAMURAI-Scramble", "DJ Mass MAD Izm*"}},
        {24058, {"Warrior", "DJ CHUCKY feat. Jonjo"}},
        {24060, {"Piano Samurai", "maras k(marasy+kors k)"}},
        {24063, {"BREAK OVER", "MASAYOSHI IIMORI"}},
        {24065, {"OTENAMI Hurricane", "t+pazolite"}},
        {24066, {"Magical", "Snail's House"}},
        {24067, {"Yellow Sketch(RX-Ver.S.P.L.)", "高田雅史"}},
        {24068, {"shuriken", "ヒゲドライバー"}},
        {24069, {"yamabiko (SINOBUZ Edition)", "かめりあ"}},
        {24070, {"九尾狐夜行", "天狐"}},
        {24071, {"Around The Galaxy", "NISH"}},
        {24072, {"Sky High", "Cuvelia"}},
        {24073, {"Snakey Kung-fu", "金獅子 vs 麒麟 feat. 獏"}},
        {24074, {"月雪に舞う華のように", "猫叉Master"}},
        {24075, {"INVISIBLE STRIX", "L.E.D."}},
        {24076, {"RAIN", "dj TAKA"}},
        {24077, {"刃図羅", "猫叉Master vs HuΣeR"}},
        {24078, {"〆", "lapix"}},
        {24079, {"BabeL ～Grand Story～", "Ako Atak"}},
        {24080, {"BroGamer", "USAO"}},
        {24081, {"Beat Juggling Mix", "Hommarju"}},
        {24082, {"SEQUENCE CAT", "SLEDLAKE (SLAKE & L.E.D.)"}},
        {24083, {"nostos", "Setaria Virtuoso"}},
        {24084, {"crew", "beatnation Records"}},
        {24085, {"Macuilxochitl", "TOMOSUKE"}},
        {24086, {"Summerlights(IIDX Edition)", "DJ Noriken"}},
        {24087, {"HAPPY★RUSH", "P*Light"}},
        {24088, {"Surf on the Light", "Tomoyuki Uchida"}},
        {24089, {"Venom", "kors k vs L.E.D.-G"}},
        {24090, {"Cyber True Color", "kors k vs Sota Fujimori"}},
        {24091, {"恋はどう？モロ◎波動OK☆方程式!!", "あべにゅうぷろじぇくと feat. 佐倉紗織 produced by ave;new"}},
        {24092, {"Vermilion", "Remo-con"}},
        {24093, {"Lost wing at.0", "猫叉Master+"}},
        {24094, {"童話回廊", "DJ TOTTO"}},
        {24095, {"Apocalypse", "Morrigan feat. リリィ"}},
        {25000, {"神謳 -RESONANCE-", "SOUND HOLIC feat. Nana Takahashi Vs.GOD PHOENIX Prim"}},
        {25001, {"THE CANNONBALLER", "L.E.D. feat. YURiCa/花たん"}},
        {25002, {"ナイトシティー・アヴァンチュール", "森永真由美"}},
        {25003, {"DEATH†ZIGOQ ～怒りの高速爆走野郎～", "L.E.D.ALiCE(DJ NAGAI Vs. BEMANI Sound Team \"L.E.D.-G\")"}},
        {25004, {"Initiation", "BEMANI Sound Team \"謎の勢力\""}},
        {25005, {"ChaserXX", "HuΣeR"}},
        {25006, {"純真可憐デザイア", "BEMANI Sound Team \"HuΣeR\" feat.Fernweh"}},
        {25007, {"EMERALDAS", "BEMANI Sound Team \"HuΣeR vs dj Hellix\""}},
        {25008, {"ANCHOR", "BEMANI Sound Team \"HuΣeR Vs. SYUNN\""}},
        {25009, {"AA -rebuild-", "D.J.Amuro"}},
        {25010, {"I Love You", "O/iviA"}},
        {25011, {"バスルーム ロマンス", "BEMANI Sound Team \"Saori Watanabe\""}},
        {25012, {"COSMIC☆WONDER☆REVOLUTION", "猫叉Master+"}},
        {25013, {"ACCELERATE", "Sota Fujimori"}},
        {25014, {"Expanded !!", "BEMANI Sound Team \"Expander\""}},
        {25015, {"Life Is A Game ft.DD\"ナカタ\"Metal", "RoughSketch"}},
        {25016, {"Back Spin Sweeper", "DJ TOTTO"}},
        {25017, {"シムルグの目醒め", "BEMANI Sound Team \"DJ TOTTO\" feat.rionos"}},
        {25018, {"Abraxas", "SYUNN"}},
        {25019, {"Papilio ulysses", "BEMANI Sound Team \"SYUNN\""}},
        {25021, {"東京神話", "DJ TECHNORCH feat.宇宙★海月 vs BEMANI Sound Team \"U1-ASAMi\""}},
        {25024, {"草原の王女-軌跡を辿って-", "劇団レコード"}},
        {25026, {"O/D*20", "Ryu*"}},
        {25027, {"255", "255"}},
        {25028, {"Battleground", "kors k"}},
        {25029, {"Boomy and The Boost", "Eagle"}},
        {25030, {"ANAGMA", "C-Show"}},
        {25031, {"ハイ*ビスカス ft. Kanae Asaba", "Xceon"}},
        {25032, {"Alpheratz", "Xceon"}},
        {25033, {"Amor De Verão", "かめりあ feat. ななひら"}},
        {25034, {"LUV DRIVE", "RoughSketch feat.Aikapin"}},
        {25035, {"HAT TRICK", "P*Light"}},
        {25036, {"Break Stasis", "Hommarju & Akira Complex"}},
        {25037, {"エディブルフラワーの独白", "OSTER project feat. 常盤ゆう"}},
        {25038, {"Exhaust Hype", "DJ Noriken"}},
        {25039, {"FREEDOM", "USAO"}},
        {25040, {"Slipstream", "lapix"}},
        {25041, {"Best of Me", "Maozon"}},
        {25042, {"Around the Future", "Maozon vs. C-Show"}},
        {25043, {"FUTURE is Dead", "C-Show"}},
        {25045, {"1001 -ESCAPE-", "SOUND HOLIC feat. Nana Takahashi"}},
        {25046, {"共犯ヘヴンズコード", "D-Evoke（与那嶺雅人/小日向翔）"}},
        {25047, {"うさ☆かめ 大戦争！", "ARM×狐夢想 feat. I've : 柚子乃 & RINA"}},
        {25048, {"Nothing but Theory", "lapix"}},
        {25049, {"Illusionary Waterlily", "DJ Noriken"}},
        {25050, {"n'pa pa BBQ", "YUC'e"}},
        {25051, {"Temple of Anubis", "Massive New Krew"}},
        {25052, {"Persephone", "Massive New Krew"}},
        {25053, {"No Limit 2 dAnce feat. 大山愛未", "Y&Co."}},
        {25054, {"Hella Deep", "MASAYOSHI IIMORI"}},
        {25055, {"Static State", "Nhato"}},
        {25056, {"Get Up! feat. Kanae Asaba", "MK"}},
        {25057, {"Midnight Lady", "Dirty Androids"}},
        {25058, {"The Chase", "DJ Mass MAD Izm*"}},
        {25059, {"UMMU", "t+pazolite"}},
        {25061, {"Chemical Cookie", "YUC'e"}},
        {25063, {"Xperanza", "aran"}},
        {25068, {"ラストセンチュリーメランコリック", "DJ Taku aka ☆Taku Takahashi (m-flo)"}},
        {25069, {"Eine Haube ～聖地の果てにあるもの～", "AIKO OI"}},
        {25070, {"Only for now", "RINA SOUND PRODUCE : KAZUYA TAKASE"}},
        {25071, {"From Time To Time", "sanodg"}},
        {25073, {"Fervidex", "Feryquitous"}},
        {25074, {"DEADHEAT", "DJ Myosuke"}},
        {25075, {"Arca", "BEMANI Sound Team \"Akhuta Works\""}},
        {25076, {"SPEED DEMON", "GUHROOVY feat. NO+CHIN"}},
        {25078, {"命の標本", "志方あきこ"}},
        {25079, {"Be a Hero!", "中島由貴"}},
        {25080, {"Raspberry Railgun", "OSTER project"}},
        {25081, {"STARLIGHT JUNCTION", "SOUND HOLIC feat. Nana Takahashi"}},
        {25082, {"Usual Days-remix", "ota2"}},
        {25083, {"Antigravity", "t+pazolite"}},
        {25084, {"バ→ビ→ブ→Bomb!", "ヒゲドライバー join. 新菜まこ & 松平なな"}},
        {25085, {"NITROUS CANNON", "かめりあ"}},
        {25086, {"パラドキシカル・タイムリープトライアル(Short Ver.)", "MOSAIC.WAV"}},
        {25088, {"encounter", "猫叉Master+"}},
        {25089, {"HYPE THE CORE", "DJ CHUCKY"}},
        {25090, {"City Never Sleeps (IIDX Edition)", "Dirty Androids"}},
        {25091, {"Rampage", "USAO"}},
        {25092, {"REVOLVER", "sky_delta"}},
        {25093, {"DropZ-Line-", "Getty vs. DJ DiA"}},
        {25094, {"Sleepless days", "猫叉Master feat.Mayumi Morinaga"}},
        {25095, {"MAXIVCORD", "BEMANI Sound Team \"dj TAKA\""}},
        {26000, {"THE DAY OF JUBILATIONS", "BEMANI Sound Team \"S-C-U vs L.E.D.\""}},
        {26001, {"KILL EACH OTHER", "BEMANI Sound Team \"L.E.D. VS. L.E.D.-G\""}},
        {26003, {"抱きしめてモナムール", "冬色AMOUR☆Prim"}},
        {26004, {"UNDERWORLD HOLOGRAPHY", "BEMANI Sound Team \"L.E.D.\" feat. KOTOKO"}},
        {26005, {"R∞tAge", "BEMANI Sound Team \"HuΣeR+\""}},
        {26007, {"X-DEN", "T.Σ.Generation"}},
        {26009, {"HEISEI", "BEMANI Sound Team \"dj TAKA\""}},
        {26010, {"Drastic Dramatic", "KING & Princess"}},
        {26011, {"GENE", "VINCENT GANATCH"}},
        {26012, {"Painful Fate", "BEMANI Sound Team \"猫叉Master\""}},
        {26015, {"Lift Us High", "BEMANI Sound Team \"Sota Fujimori\""}},
        {26016, {"CODE:0", "BEMANI Sound Team \"HEXA\""}},
        {26017, {"BLO§OM", "BEMANI Sound Team \"TAG\""}},
        {26018, {"ZENDEGI DANCE", "ARM × BEMANI Sound Team \"U1 overground\""}},
        {26019, {"Psycho Sheep Riddim", "BEMANI Sound Team \"SYUNN\""}},
        {26020, {"COSMIC CYBER", "BEMANI Sound Team \"Captain Sonic\""}},
        {26023, {"Garuda", "kors k"}},
        {26024, {"グラナダの風", "BEMANI Sound Team \"劇団レコード\""}},
        {26025, {"Unbelief", "BEMANI Sound Team \"Anonymous\""}},
        {26026, {"CoMAAAAAAA", "Ryu☆"}},
        {26027, {"深愛のリグレット", "Xceon feat.Mayumi Morinaga"}},
        {26028, {"Wonderland", "kors k"}},
        {26029, {"Mächö Mönky", "kors k"}},
        {26030, {"Glory", "kradness"}},
        {26031, {"夏の匂い。キミの残像。 ft. Kanae Asaba", "Xceon"}},
        {26033, {"Catch Our Fire!", "中島由貴"}},
        {26034, {"dAuntl3ss", "DJ Noriken"}},
        {26036, {"Wing of Hearts", "USAO & DJ Nanashi"}},
        {26037, {"Carmina", "CANVAS feat. Quimär"}},
        {26038, {"L.F.O", "aran"}},
        {26039, {"The Rebellion of Sequencer", "DJ Myosuke"}},
        {26040, {"泰東ノ翠霞", "bermei.inazawa/feat.霜月はるか"}},
        {26041, {"花冠 feat.Aikapin", "RoughSkreamZ"}},
        {26042, {"セカンドピアス", "OSTER project feat. echo"}},
        {26043, {"Dr. Chemical & Killing Machine", "Hommarju"}},
        {26044, {"ハードベース・フェスタ", "かめりあ feat. ななひら"}},
        {26046, {"IDC feat.REVERBEE (Mo'Cuts Ver)", "DJ Mass MAD Izm*"}},
        {26047, {"Red. by Jack Trance", "DJ Mass MAD Izm*"}},
        {26048, {"Twilight Warp", "Maozon feat. Kyte"}},
        {26049, {"ROCK女 feat. 大山愛未, Ken", "Y&Co."}},
        {26050, {"Yum Yum Jelly", "YUC'e"}},
        {26051, {"LADYBIRD", "YUC'e"}},
        {26052, {"Cranberry City ft. Luschel", "lapix"}},
        {26053, {"& Intelligence", "lapix"}},
        {26054, {"Hurry Hurry", "Masayoshi Iimori"}},
        {26055, {"Ember Lights", "Nhato"}},
        {26058, {"Urban Constellations", "Dirty Androids"}},
        {26059, {"ONIGOROSHI", "m1dy"}},
        {26060, {"爆ゼニ☆がってんワーカー", "ARM×狐夢想 feat. ななひら"}},
        {26063, {"The Best of Both Worlds", "☆Taku Takahashi (m-flo, block.fm)"}},
        {26064, {"GIGA THRASH", "Blacklolita"}},
        {26066, {"ミストレス・アンに花束を", "soejima takuma feat.BEMANI Sound Team \"猫叉Master\""}},
        {26067, {"SPEED ROCKER", "AJURIKA"}},
        {26068, {"IDOL syndrome.", "RINA"}},
        {26069, {"OVER TIME", "空中分解feat.アンテナガール"}},
        {26070, {"Xlø", "sasakure.UK"}},
        {26071, {"Let me be your cure", "Pizuya's Cell"}},
        {26072, {"Level One", "Yamato"}},
        {26074, {"Next Tales 2 Oath (IIDX 20th Anniv \"Ring\" Theme)", "Hommarju"}},
        {26076, {"龍王の霊廟(Mausoleum Of The Primal Dragon)", "BEMANI Sound Team \"黒猫ダンジョン\""}},
        {26077, {"Wolf 1061", "Xceon"}},
        {26078, {"金野火織の金色提言", "DJ TECHNORCH feat. 宇宙★海月"}},
        {26079, {"EVANESCENT", "SOUND HOLIC feat. Nana Takahashi"}},
        {26080, {"LOST TECHNOLOGIE", "かめりあ"}},
        {26081, {"XENON II ～TOMOYUKIの野望～", "Mr.T"}},
        {26082, {"REPLAY", "SLAKE"}},
        {26083, {"DRUNK MONKY", "DJ ODDBALL"}},
        {26084, {"Playing With Fire", "kors k"}},
        {26085, {"Lethal Weapon", "BEMANI Sound Team \"HuΣeR\""}},
        {26086, {"GO OVER WITH GLARE -ROOTAGE 26-", "BEMANI Sound Team \"L.E.D.-G\""}},
        {26087, {"お菓子の王国", "Snail's House"}},
        {26088, {"50th Memorial Songs -Beginning Story-", "BEMANI Sound Team"}},
        {26089, {"50th Memorial Songs -二人の時 ～under the cherry blossoms～-", "BEMANI Sound Team"}},
        {26090, {"50th Memorial Songs -Flagship medley-", "BEMANI Sound Team"}},
        {26091, {"50th Memorial Songs -The BEMANI History-", "BEMANI Sound Team"}},
        {26092, {"Night! Night! Night!", "MM"}},
        {26093, {"ruin of opals", "上ノ瀬つかさ"}},
        {26094, {"Technicolour Dreams", "DUNE & M-Project & GUHROOVY"}},
        {26095, {"Carry Me Away", "lapix"}},
        {26097, {"ToyCube Pf.(RX-Ver.S.P.L.)", "高田雅史"}},
        {26099, {"Necroxis Girl", "BEMANI Sound Team \"HuΣeR\""}},
        {26101, {"Geirskögul", "Maozon"}},
        {26104, {"HARD BRAIN", "AJURIKA"}},
        {26106, {"Visterhv", "Feryquitous"}},
        {26107, {"Trill auf G", "BEMANI Sound Team \"dj TAKA\""}},
        {26108, {"voltississimo", "BEMANI Sound Team \"PHQUASE\""}},
        {26109, {"toy boxer", "BEMANI Sound Team \"S-C-U & SYUNN\""}},
        {26110, {"最小三倍完全数", "DJ TECHNORCH"}},
        {26112, {"おーまい！らぶりー！すうぃーてぃ！だーりん！", "BEMANI Sound Team \"PON\" feat.NU-KO"}},
        {26113, {"Afterimage d'automne", "BEMANI Sound Team \"猫叉劇団\""}},
        {26114, {"BLACK JACKAL", "Akira Complex"}},
        {26115, {"ミッドナイト☆WAR", "いちか"}},
        {27000, {"THE BRAVE MUST DIE", "BEMANI Sound Team \"L.E.D.-G\""}},
        {27001, {"UNITE THE HEART", "BEMANI Sound Team \"T.Kakuta\" feat. 709sec. / 花たん"}},
        {27002, {"PHASE SHIFT MANEUVER", "BEMANI Sound Team \"L.E.D.\""}},
        {27003, {"がっつり陰キャ!? 怪盗いいんちょの億劫^^;", "噂の怪盗少女ぷらずま★彡Prim@休業中～( _ _ ).。"}},
        {27004, {"Dans la nuit de l'éternité", "BEMANI Sound Team \"レ・度胸兄弟\""}},
        {27005, {"VALKYRIAS -英雄誕生-", "BEMANI Sound Team \"HuΣeR\" feat.Fernweh"}},
        {27007, {"LIGHTNING STRIKES", "BEMANI Sound Team \"HuΣeR\""}},
        {27008, {"EROICA", "BEMANI Sound Team \"HERO\""}},
        {27009, {"TECHNO Style Essentials", "BEMANI Sound Team \"SETUP from Berlin\""}},
        {27010, {"27th style", "三代目 \"dj TAKA & DAYBREAKERS\""}},
        {27011, {"rough percussionythm", "BEMANI Sound Team \"setup VS 謎の勢力\""}},
        {27012, {"LASER CRUSTER (IGNITE REMIX)", "Remixed by BEMANI Sound Team \"HuΣeR\""}},
        {27013, {"錬成人間トリコロイダー", "DJ SHARPNEL feat. ￥Ｃｕスタ平"}},
        {27014, {"Like+it!", "Ryu☆"}},
        {27015, {"Hold My Hand", "BEMANI Sound Team \"Sota Fujimori\""}},
        {27016, {"STOIC HYPOTHESIS", "BEMANI Sound Team \"Expander\""}},
        {27017, {"Fly Above (Vicissitude Remix)", "Remixed by BEMANI Sound Team \"PHQUASE\""}},
        {27018, {"華麗なる大犬円舞曲", "Wiktoria"}},
        {27019, {"AKASHIC BREAK", "BEMANI Sound Team \"TAG\""}},
        {27020, {"Everlasting Message", "ぺのれり"}},
        {27021, {"Queen Kaguya", "BEMANI Sound Team \"U1 overground\""}},
        {27022, {"Do What You Want", "BEMANI Sound Team \"SYUNN\""}},
        {27023, {"Lost Souls", "BEMANI Sound Team \"SYUNN\""}},
        {27024, {"曼荼羅恋々", "BEMANI Sound Team \"Akhuta Works\" feat. Nana Takahashi"}},
        {27025, {"OUTER PLANETS", "BEMANI Sound Team \"劇団レコード\""}},
        {27026, {"魅惑のYUMMYスイーツ", "BEMANI Sound Team \"TATSUYA\""}},
        {27029, {"Nasty Techniques", "kors k"}},
        {27030, {"Rave Patroller", "Eagle"}},
        {27031, {"Sugar Drippin'", "kors k"}},
        {27032, {"セピアの軌跡 ft. 天宮みや(少女フラクタル)", "Xceon"}},
        {27033, {"Bow shock!!", "Xceon"}},
        {27034, {"T-REX vs Velociraptor (In the Far east euphoria)", "RoughSketch & TARACHINE"}},
        {27035, {"Artist", "CANVAS feat. Quimär"}},
        {27036, {"GHOST", "Hommarju"}},
        {27037, {"The Sky of Sadness", "猫叉Master"}},
        {27039, {"Lords Of The Roundtable", "DJ Mass MAD Izm* feat.REO"}},
        {27041, {"Rainstorm", "Maozon feat. Chica"}},
        {27043, {"Primitive Vibes", "lapix"}},
        {27044, {"Double Dribble", "lapix"}},
        {27045, {"Virus Funk", "Nhato"}},
        {27046, {"Override", "Nhato"}},
        {27047, {"Voo Doo Bamboleo", "SOUND HOLIC Vs. ZYTOKINE feat. CALEN"}},
        {27048, {"Infinity Mirror", "Dirty Androids"}},
        {27049, {"灼熱Beach Side Bunny (Masayoshi Iimori Remix)", "Remixed by Masayoshi Iimori"}},
        {27050, {"Volcanic Dragon", "DJ Shimamura"}},
        {27051, {"Ska-sh All Neurons!!", "かめりあ feat. ななひら"}},
        {27052, {"SCREW // owo // SCREW", "かめりあ"}},
        {27053, {"Calvados Queen", "OSTER project feat. かなたん"}},
        {27054, {"深淵に捧ぐレクイエム", "OSTER project"}},
        {27056, {"Matt Silver", "Remo-con"}},
        {27058, {"Moving on", "AJURIKA feat.矢吹真央"}},
        {27059, {"TRIUMPH", "AJURIKA"}},
        {27060, {"BEAT PRISONER", "AJURIKA"}},
        {27061, {"Change Yourself", "ARM × kradness"}},
        {27062, {"NEWALONE", "Masayoshi Iimori"}},
        {27063, {"beatAffection", "ビートまりお"}},
        {27064, {"Friction[!]Function", "Feryquitous"}},
        {27065, {"GIGA VIOLATE", "Blacklolita"}},
        {27066, {"Crank It", "Crayvxn"}},
        {27069, {"S!ck (Nhato Remix)", "Remixed by Nhato"}},
        {27070, {"Beautiful Harmony (IIDX Mix)", "Ryu☆"}},
        {27074, {"fairy cocktail", "Tomggg"}},
        {27075, {"Mel", "Applekid"}},
        {27076, {"Hyper Drive feat. ぷにぷに電機", "パソコン音楽クラブ"}},
        {27077, {"Theory", "YUTO"}},
        {27078, {"Level 2", "Yamato"}},
        {27079, {"And-RoiD", "Fujishiro feat.KNA"}},
        {27080, {"ランカーキラーガール", "中島由貴 × いちか"}},
        {27081, {"VIBRΛ", "Nhato Vs. MK"}},
        {27083, {"Silly Love", "DÉ DÉ MOUSE"}},
        {27084, {"Inferno of Fomalhaut", "fallen shepherd ft. ricono"}},
        {27087, {"開きたまえ！Next stAge！", "librarians of Rootage (Ripnte, Stampa and Cleep)"}},
        {27088, {"ピアノ協奏曲第1番”蠍火” (BlackY Remix)", "Remixed by BlackY"}},
        {27090, {"Shiva", "Relect"}},
        {27092, {"Backyard Stars", "TAKU INOUE"}},
        {27094, {"THE F∀UST", "Masqed Pierrot"}},
        {27095, {"Smashing Wedge", "nora2r"}},
        {27096, {"Advent Infamous", "Blacklolita"}},
        {27100, {"If", "Pa's Lam System"}},
        {27101, {"take me higher", "KOTONOHOUSE"}},
        {27102, {"Vinculum stellarum", "iconoclasm"}},
        {27103, {"眠りの国のステラ", "BEMANI Sound Team \"DJ TOTTO\""}},
        {27105, {"ラブキラ☆スプラッシュ", "BEMANI Sound Team \"Sota F.\" feat.いちか"}},
        {27106, {"Sparkle Smilin'", "BEMANI Sound Team \"Qrispy Joybox\" feat.いちか"}},
        {27107, {"狂水一華", "BEMANI Sound Team \"HuΣeR Vs. SYUNN\" feat.いちか"}},
        {27108, {"Into The Madness", "Yuta Imai"}},
        {27109, {"ORCA", "かめりあ"}},
        {27110, {"バッドエンド・シンドローム", "アリスシャッハと魔法の楽団"}},
        {27112, {"Forgetting Machine", "TAKU INOUE"}},
        {27113, {"シャムシールの舞", "Zektbach"}},
        {27114, {"Megalara Garuda", "SYUNN"}},
        {27116, {"Ypsilon", "BEMANI Sound Team \"setup\""}},
        {28000, {"涙のテ・エストラーニョ・ムーチョ", "LA BAILARINA☆Prim"}},
        {28001, {"Romanticが止まらない", "Remixed by BEMANI Sound Team \"L.E.D.\" & IOSYS"}},
        {28002, {"THE PEERLESS UNDER HEAVEN", "Yuta Imai Vs. BEMANI Sound Team \"L.E.D.-G\""}},
        {28004, {"無意識のフィロソフィア", "BEMANI Sound Team \"TAG\""}},
        {28005, {"∀", "BEMANI Sound Team \"HuΣeR\" respect for D.J.Amuro"}},
        {28007, {"LOCUS OF THE TRAVEL", "CANVAS feat. Quimär & BEMANI Sound Team \"L.E.D.-G\""}},
        {28008, {"ディスコルディア", "ぺのれり vs. BEMANI Sound Team \"HuΣeR\""}},
        {28009, {"of the first magnitude", "BEMANI Sound Team \"Trance Liquid\""}},
        {28010, {"X-ray binary", "BEMANI Sound Team \"Trance Liquid\""}},
        {28011, {"-65℃", "BEMANI Sound Team \"D.J.Amuro\""}},
        {28014, {"Euphoric Lagoon", "BEMANI Sound Team \"TAG\""}},
        {28015, {"儚き恋の華", "BEMANI Sound Team \"TAG\" feat. 猫体質"}},
        {28016, {"水鏡の異界", "BEMANI Sound Team \"Coyaan\""}},
        {28017, {"Pārvatī", "BEMANI Sound Team \"U1 overground\""}},
        {28018, {"S-Bahn", "BEMANI Sound Team \"DARK TRAIN\""}},
        {28019, {"COSMIC RAY", "BEMANI Sound Team \"Captain Sonic\""}},
        {28020, {"乱膳の舞姫", "BEMANI Sound Team \"Akhuta Works\" feat. mami"}},
        {28021, {"Vitrum", "BEMANI Sound Team \"Yvya\""}},
        {28022, {"霧幻メモリア", "BEMANI Sound Team \"劇団レコード\" feat.Risa Yuzuki"}},
        {28023, {"Winner's Proof ft. KANASA from bless4", "BEMANI Sound Team \"HuΣeR\" & kors k"}},
        {28024, {"Sinus Iridum", "神楽改"}},
        {28025, {"Empire of Fury", "kors k"}},
        {28027, {"Tiempo Loco", "kors k feat.Hboy"}},
        {28028, {"水無月の雫 ft. 小林まな", "Xceon"}},
        {28029, {"Rubrum Piano", "Xceon"}},
        {28030, {"閠槞彁の願い", "DJ TECHNORCH & RoughSketch"}},
        {28031, {"Midnight Drive", "らっぷびと Prod. by uno"}},
        {28032, {"Lovely Howdy Cowboy!!", "まろん feat. キャサリン"}},
        {28033, {"Frisk And Squeak", "nora2r"}},
        {28035, {"MEGAERA", "fallen shepherd × cotowari ft. nayuta"}},
        {28036, {"Here We Are", "The 4th feat.ここなつ"}},
        {28037, {"IIDX RED Ending (Ryu☆Remix)", "Remixed by Ryu☆"}},
        {28038, {"The Wind of China Express(The 4th Mashup)", "The 4th"}},
        {28039, {"WAKE UP NOW", "Maozon feat. Chica"}},
        {28040, {"As You Want", "Maozon"}},
        {28041, {"Rowdy", "Dazsta"}},
        {28042, {"Swarm Of Scarabs", "C-Show"}},
        {28043, {"魔法のかくれんぼ", "Snail's House"}},
        {28044, {"Don't Stop The Music feat. Kanae Asaba", "Nhato"}},
        {28045, {"Dawn Saga", "Nhato"}},
        {28046, {"AMRITA -不滅ノ花-", "SOUND HOLIC feat. Nana Takahashi"}},
        {28047, {"Farewell to Marrakech", "Dirty Androids"}},
        {28048, {"Danza Aestas", "Feryquitous"}},
        {28049, {"Ritual of Anubis", "KO3 & Relect"}},
        {28050, {"POLꞰAMAИIA", "かめりあ feat. ななひら"}},
        {28051, {"ASIAN VIRTUAL REALITIES (MELTING TOGETHER IN DAZZLING DARKNESS)", "かめりあ"}},
        {28052, {"犬に雨傘", "OSTER project feat. そらこ"}},
        {28053, {"innocent revolver", "OSTER project"}},
        {28055, {"Viridian", "REMO-CON"}},
        {28056, {"Jungle Eater", "Hommarju"}},
        {28057, {"LAST DAY", "AJURIKA"}},
        {28058, {"BIGソムタム", "AJURIKA"}},
        {28059, {"Burning Flame", "AJURIKA feat.SAK."}},
        {28060, {"GIGA RAID", "Blacklolita"}},
        {28061, {"rommmo", "callasoiled"}},
        {28062, {"Para siempre", "削除 feat. 削除"}},
        {28064, {"Ah Hah Yeah", "Masayoshi Iimori"}},
        {28065, {"apo:llioth", "Juggernaut."}},
        {28066, {"Explorer feat. ぷにぷに電機", "パソコン音楽クラブ"}},
        {28067, {"Overslept", "PARKGOLF"}},
        {28069, {"Tell me what you wish feat.らっぷびと", "Pizuya's Cell"}},
        {28070, {"Ocean Blue feat. Luschel", "lapix"}},
        {28071, {"Rosa azuL", "lapix"}},
        {28072, {"When I Met U", "LADY'S ONLY"}},
        {28073, {"BLACK or WHITE?", "BlackYooh vs. siromaru"}},
        {28074, {"新宝島", "Remixed by BEMANI Sound Team \"TAG feat. PON\""}},
        {28076, {"Zenith", "Snail's House"}},
        {28077, {"HIGH VOLTAGE", "Yuta Imai"}},
        {28079, {"Chewingood!!!", "TORIENA"}},
        {28080, {"Crazy Jackpot", "Hommarju"}},
        {28081, {"二人ノ廃城幽踊宴", "上ノ瀬つかさ"}},
        {28082, {"Sugarplum", "KOTONOHOUSE"}},
        {28083, {"That Feeling", "Crayvxn"}},
        {28084, {"Ignis†Iræ", "BEMANI Sound Team \"神\""}},
        {28085, {"OTOKOZAKA", "BEMANI Sound Team \"Trance Liquid\""}},
        {28086, {"Neo Heritage", "kors k vs MAD CHILD"}},
        {28087, {"SOLID STATE SQUAD -RISEN RELIC REMIX-", "Remixed by xi"}},
        {28088, {"ABSOLUTE (kors k Remix)", "Remixed by kors k"}},
        {28089, {"smooooch・∀・ (Snail's House Remix)", "Remixed by Snail's House"}},
        {28090, {"バッド・スイーツ、バッド・ドリーム", "かめりあ feat. ななひら"}},
        {28091, {"世界の果てに約束の凱歌を -ReUnion-", "OSTER project feat. かなたん"}},
        {28092, {"ここからよろしく大作戦143", "BEMANI Sound Team \"あさき隊\""}},
        {28093, {"伐折羅-vajra-", "DJ TOTTO VS 兎々"}},
        {28096, {"Level 3", "Yamato"}},
        {28098, {"BEMANI PRO LEAGUE Theme", "BEMANI Sound Team \"Sota F.\""}},
        {28100, {"Fire Beat", "kors k"}},
        {28102, {"DENIM", "SLAKE"}},
        {28109, {"MA・TSU・RI", "かなたん,アマギセーラ,ぁゅ by BEMANI Sound Team \"藤森崇多\""}},
        {28110, {"MOVE! (We Keep It Movin')", "Jonny Dynamite!,Lisa - paint with stars -,Rio Hiiragi by BEMANI "}},
        {28112, {"スーパー戦湯ババンバーン", "すわひでお,秋成,かぼちゃ,藍月なくる,NU-KO by BEMANI Sound Team \"八戸亀生羅\""}},
        {28113, {"Globe Glitter", "Sana,ATSUMI UEDA by BEMANI Sound Team \"PON\""}},
        {28114, {"DUAL STRIKER", "Mayumi Morinaga,Fernweh by BEMANI Sound Team \"L.E.D. & HuΣeR\""}},
        {28117, {"Rejection Girl", "BEMANI Sound Team \"HuΣeR\""}},
        {29000, {"LIVE DRIVING!! feat. 花たん", "BEMANI Sound Team \"S-C-U vs L.E.D.\""}},
        {29001, {"SOLID WYVERN", "BEMANI Sound Team \"L.E.D.\""}},
        {29002, {"GRAVITON", "BEMANI Sound Team \"L.E.D.\""}},
        {29003, {"PLASMA SOUL NIGHT feat. Nana Takahashi / 709sec.", "BEMANI Sound Team \"L.E.D.\""}},
        {29005, {"HEARTACHE", "BEMANI Sound Team \"HuΣeR\" feat.ゆきまめ"}},
        {29006, {"Onyx", "BEMANI Sound Team \"HuΣeR\""}},
        {29007, {"ALTERNATOR", "BEMANI Sound Team \"dj Hellix\""}},
        {29008, {"ANEMONE", "BEMANI Sound Team \"HuΣeR × Yvya\" feat.紫村 花澄"}},
        {29009, {"Tail Lights", "BEMANI Sound Team \"dj TAKA\" feat.nana hatori"}},
        {29010, {"Binary Black Hole", "BEMANI Sound Team \"D.J.Amuro\""}},
        {29011, {"Divine Heaven", "Absolute The 4th"}},
        {29012, {"ハイテックトキオ", "lapix ∞ BEMANI Sound Team \"Sota Fujimori\""}},
        {29013, {"AMICABLE", "BEMANI Sound Team \"Sota F.\""}},
        {29015, {"ウツシミウツシ", "BEMANI Sound Team \"PHQUASE\" feat.ぁゅ"}},
        {29016, {"SPARK IN THE NIGHT", "BEMANI Sound Team \"L.E.D.-G\""}},
        {29017, {"ピアノ独奏無言歌 \"灰燼\"", "BEMANI Sound Team \"Virkato Wakhmaninov\""}},
        {29018, {"DISPARATE", "BEMANI Sound Team \"Captain Sonic\""}},
        {29019, {"Pout", "BEMANI Sound Team \"SYUNN\""}},
        {29020, {"DREAM OF SPACE UFO ABDUCTION", "BEMANI Sound Team \"謎の宇宙人スペースX\""}},
        {29021, {"Lawes's Parotia", "BEMANI Sound Team \"Yvya\""}},
        {29022, {"PIRATES BLADE", "BEMANI Sound Team \"劇団レコード\""}},
        {29024, {"Prohibited Props", "BEMANI Sound Team \"ZAQUVA\""}},
        {29025, {"Purple Perplex", "Eagle"}},
        {29026, {"kors k's How to make OTOGE CORE", "kors k"}},
        {29027, {"2 Beasts Unchained", "kors k vs Yooh"}},
        {29028, {"愛しくてラヴィンユー ft. マナ", "Xceon"}},
        {29029, {"Fegrix", "Xceon vs DJ Command (Eurobeat Union)"}},
        {29030, {"GiGaGaHell", "m1dy, RoughSketch"}},
        {29033, {"Xyndrome", "nora2r"}},
        {29035, {"Wonderful Escape", "DÉ DÉ MOUSE"}},
        {29036, {"FINALLY BLAZE", "BlackY"}},
        {29037, {"Victory Of Ravers", "DJ Shimamura"}},
        {29038, {"青の洞窟", "Ujico*"}},
        {29039, {"Banger Banger Banger Banger", "nora2r"}},
        {29040, {"Get set, Go! feat.Kanae Asaba", "MK"}},
        {29041, {"天邪鬼", "Qlarabelle"}},
        {29042, {"RAGE feat.H14 of LEONAIR", "DJ Mass MAD Izm*"}},
        {29043, {"Fantastic Merry-Go-Round", "SOUND HOLIC feat. Nana Takahashi"}},
        {29044, {"Blue Bird feat. Kanae Asaba", "Nhato"}},
        {29045, {"禊", "Nhato"}},
        {29046, {"Ariah", "satella feat.藍月なくる"}},
        {29047, {"Nocturnal 2097", "Dirty Androids"}},
        {29049, {"Flying Castle", "lapix"}},
        {29050, {"WHA", "かめりあ involving ななひら"}},
        {29051, {"N.O.", "かめりあ"}},
        {29052, {"烽火連天の刃", "OSTER project"}},
        {29053, {"オールトの雲", "OSTER project"}},
        {29054, {"Smalt #28598F", "REMO-CON"}},
        {29055, {"Ergosphere", "TOMOSUKE"}},
        {29056, {"EMOTiON TRiPPER", "sky_delta"}},
        {29057, {"808monkey", "AJURIKA"}},
        {29058, {"10000 MILES AWAY", "AJURIKA"}},
        {29060, {"口カラ凸ゲキ", "SARUKANI × Blacklolita"}},
        {29061, {"n/a", "Blacklolita"}},
        {29062, {"Angel's Ladder", "xi"}},
        {29063, {"Ventriloquist", "Avans"}},
        {29064, {"Non Stop Rock", "Masayoshi Iimori"}},
        {29065, {"ナイトフィクション", "中山真斗 feat. CHAN"}},
        {29066, {"hard-wired", "Yuta Imai ≡ Blacklolita"}},
        {29068, {"雪上断火", "Des-ROW・組"}},
        {29069, {"No Day But Today!", "NU-KO & yunocy"}},
        {29070, {"Arkadia", "Hommarju ft. Mayumi Morinaga"}},
        {29074, {"アクマフカ", "Pizuya's Cell"}},
        {29075, {"シル・ヴ・プレジデント", "P丸様。"}},
        {29076, {"Don't believe the hype", "DJ Mass MAD Izm* feat.H14(LEONAIR)"}},
        {29077, {"P.O.W.E.R.", "Yuta Imai"}},
        {29078, {"ABSOLUTE EVIL", "Yuta Imai"}},
        {29079, {"月とミルク", "TORIENA"}},
        {29080, {"めでてえ", "TORIENA"}},
        {29081, {"怪物", "Remixed by Nhato feat. ricono"}},
        {29082, {"ミュージック・アワー", "Remixed by BEMANI Sound Team \"PON\""}},
        {29084, {"Silver Bullet", "xi"}},
        {29085, {"オドループ", "フレデリック"}},
        {29086, {"《GRANDMASTER》", "Blacklolita"}},
        {29087, {"Game Changers", "Yuta Imai"}},
        {29088, {"Hat Surprise", "Hommarju"}},
        {29089, {"TOMAHAWK", "かめりあ"}},
        {29090, {"One for All", "RoughSketch"}},
        {29091, {"Brave Spirits", "MK"}},
        {29092, {"Triple Cross", "BEMANI Sound Team \"dj TAKA & DJ YOSHITAKA & SYUNN\""}},
        {29093, {"Aftermath", "BEMANI Sound Team \"猫叉Master & あさき & Yvya\""}},
        {29094, {"逆月", "BEMANI Sound Team \"HuΣeR\" feat.Fernweh"}},
        {29095, {"Souhait bleu", "しーけー"}},
        {29096, {"Harmonia", "ATSUMI UEDA"}},
        {29097, {"Stepper", "PSYQUI"}},
        {29098, {"Push on Beats!～音ゲの国のeX-ストリーマー～", "MOSAIC.WAV"}},
        {29099, {"黒紅掬い", "猫叉Master feat.霜月はるか"}},
        {29100, {"Emera", "PON"}},
        {29102, {"グッバイ宣言", "Remixed by uno(IOSYS) & Liqo feat. Chiyoko"}},
        {30000, {"B.O.D.Y.", "BEMANI Sound Team \"L.E.D. Sota F.\"& Starbitz"}},
        {30001, {"湘南ロンリーMIDNIGHT RAIN", "Nana Takahashi & BEMANI Sound Team \"T.Kakuta\""}},
        {30002, {"LOUDER ROLLING THUNDER", "BEMANI Sound Team \"Dustup Vs. L.E.D.-G\""}},
        {30004, {"Shadow World", "BEMANI Sound Team \"HuΣeR × 猫叉Master\" feat.Emi Evans"}},
        {30005, {"TECHNOPHOBIA", "BEMANI Sound Team \"HuΣeR\""}},
        {30006, {"[ ]DENTITY", "BEMANI Sound Team \"HuΣeR\""}},
        {30007, {"VØID", "BEMANI Sound Team \"Darker Vs. JUSTICE\""}},
        {30008, {"FLARE -炎舞- ft.Nana Takahashi", "BEMANI Sound Team \"dj TAKA\" Vs SOUND HOLIC"}},
        {30009, {"No Border", "BEMANI Sound Team \"dj TAKA\" feat.Sana"}},
        {30010, {"輪廻の鴉", "BEMANI Sound Team \"dj TAKA\""}},
        {30011, {"STRAIGHT TO THE STARS", "BEMANI Sound Team \"Expander\" feat. Starbitz"}},
        {30012, {"Xerulean", "BEMANI Sound Team \"ZAQUVA\""}},
        {30014, {"サヨナラ・ヘヴン-Celtic Chip Dance Mix-", "しのりゅー"}},
        {30015, {"VOLAQUAS", "BEMANI Sound Team \"DJ TOTTO VS 兎々\""}},
        {30016, {"7 Colors", "kors k feat.吉河順央"}},
        {30017, {"少年リップルズ", "常盤ゆう"}},
        {30018, {"■□模様", "BEMANI Sound Team \"PHQUASE\" feat.紫崎 雪"}},
        {30019, {"LADS", "BEMANI Sound Team \"PON\""}},
        {30020, {"Meissa", "BEMANI Sound Team \"Yvya\""}},
        {30022, {"雨のちパノラマセカイ", "BEMANI Sound Team \"劇団レコード\" feat.NU-KO"}},
        {30024, {"Bad Encryption", "BEMANI Sound Team \"ZAQUVA\" respect for teranoid"}},
        {30025, {"Beyond Evolution", "Hekatoncheir"}},
        {30026, {"Programmed Genom", "kors k"}},
        {30027, {"kors k's How to make OTOGE CORE 「LONG」", "kors k"}},
        {30028, {"suspicions", "BEMANI Sound Team \"猫叉Master VS dj TAKA\""}},
        {30029, {"≡+≡", "Ryu☆"}},
        {30030, {"Caldwell 99", "BlackY"}},
        {30031, {"月と夢の跡 ft. マナ", "Xceon"}},
        {30032, {"Ambush Ace", "Xceon"}},
        {30033, {"C-C-C-N-N-N", "RoughSkreamZ feat. Aikapin"}},
        {30034, {"Peaktime Booster", "らっぷびと Prod. by RoughSketch & NUE"}},
        {30036, {"儚キ戀ノ幻想譚", "まろん feat. あやぽんず＊ (森羅万象)"}},
        {30037, {"Always We Trust In You", "nora2r"}},
        {30038, {"With You", "BANVOX"}},
        {30039, {"3V0", "BlackY"}},
        {30040, {"Driver", "Masayoshi Iimori"}},
        {30041, {"きゅんです。", "Pizuya's Cell"}},
        {30042, {"Ruler or Loser", "Maozon feat. Nadia"}},
        {30043, {"Rewind Time", "Dazsta"}},
        {30045, {"wanna be a \"BAD GIRL\" feat. Nana Takahashi", "Nhato"}},
        {30046, {"Fading Stars", "Nhato"}},
        {30047, {"Seraph", "satella feat.棗いつき"}},
        {30048, {"Perfect Plan", "Dirty Androids"}},
        {30049, {"Swing My Wonderland", "lapix"}},
        {30051, {"Summerblue", "Toby Fox & Camellia"}},
        {30052, {"Somnidiscotheque", "夢路 歩"}},
        {30053, {"罪過の聖堂", "OSTER project"}},
        {30054, {"栄冠のカンパネラ", "OSTER project"}},
        {30055, {"dica dica", "REMO-CON"}},
        {30056, {"Super Freak", "Hommarju"}},
        {30057, {"楽園追放", "中山真斗 feat. CHAN"}},
        {30058, {"#CMFLG", "Qlarabelle"}},
        {30059, {"神のシナリオ", "AJURIKA"}},
        {30060, {"glacia", "DJ TOTTO"}},
        {30061, {"EXODUS SIGN", "Blacklolita"}},
        {30063, {"GET UP AGAIN", "Zekk feat. くらべ"}},
        {30064, {"チェイスチェイスジョーカーズのうた (オニスタイルリミックス)", "ちよこ & 一ノ瀬 月琉 Prod. by RoughSketch & NUE"}},
        {30065, {"BIGWAVERS", "BlackY"}},
        {30066, {"VOLCANIC BIGBEAT", "DJ Mass MAD Izm*"}},
        {30067, {"Dreaming Dream", "MK feat. 紫咲ほたる"}},
        {30068, {"THE TIME MACHINE", "Yuta Imai"}},
        {30069, {"ONE AND ONLY", "Yuta Imai"}},
        {30070, {"CUE CUE RESCUE", "TORIENA"}},
        {30072, {"あるビー！ feat.ころねぽち", "ヒゲドライバー"}},
        {30073, {"真夜中のバベル", "Len"}},
        {30075, {"Sunny Day Vibes", "Mameyudoufu"}},
        {30076, {"The Clown of 24stairs", "Yu_Asahina"}},
        {30077, {"ZEИITH", "Ashrount vs polysha"}},
        {30078, {"ぞうしょく！？マイデンティティ", "DJ SHARPNEL feat. みらい"}},
        {30079, {"Level 4", "Yamato"}},
        {30080, {"Chaotoxin", "Feryquitous"}},
        {30081, {"昏き甲鉄のヴェルガ", "arcane feat.rionos"}},
        {30082, {"おとせサンダー", "ぼっちぼろまる"}},
        {30086, {"《ORDERBREAKER》", "Blacklolita"}},
        {30087, {"OVER VOLTAGE", "Yuta Imai"}},
        {30088, {"Hat Surprise (Season 2)", "Hommarju"}},
        {30089, {"Ōu Legends", "かめりあ"}},
        {30090, {"Red Soul", "RoughSketch"}},
        {30091, {"STAR BEAT", "MK"}},
        {30092, {"Get On Your Feet", "Nhato"}},
        {30093, {"Next Level", "Maozon"}},
        {30094, {"24h Endurance Race", "BEMANI Sound Team \"Risk Junk\""}},
        {30095, {"I", "黒魔"}},
        {30096, {"RINИE", "GeMiNioИ"}},
        {30097, {"パーフェクトイーター", "BEMANI Sound Team \"PON\" feat.かなたん"}},
        {30098, {"恋愛＝精度×認識力", "立秋 vs. BEMANI Sound Team \"L.E.D.-G\" feat.ちょこ＆ななひら"}},
        {30099, {"AWA AWA", "Snail's House"}},
        {30100, {"ちょえちょえまぎか", "Pizuya's Cell"}},
        {30101, {"神っぽいな", "Remixed by uno(IOSYS) & NUE feat. Chiyoko"}},
        {30102, {"KING", "Remixed by SOUND HOLIC feat. はるの"}},
        {30106, {"CODE -CRiMSON-", "Shiron"}},
        {30107, {"MAX 360", "BEMANI Sound Team \"[x]\""}},
        {30108, {"異心前進♪ぴょんぴょんぴょん", "天土"}},
        {30109, {"惑星☆ロリポップ", "SOUND HOLIC feat. Nana Takahashi"}},
        {30111, {"Shamshir", "Blacklolita"}},
        {30114, {"Stylus", "BEMANI Sound Team \"HuΣeR\""}},
        {31000, {"JUSTICE/GUILTY feat. Nana Takahashi & 709sec.", "BEMANI Sound Team \"L.E.D.\""}},
        {31001, {"CADENZA", "lapix ∞ BEMANI Sound Team \"L.E.D.\""}},
        {31003, {"The Last Apocalypse", "BEMANI Sound Team \"Sota F. feat. Yvya\""}},
        {31004, {"Iris", "BEMANI Sound Team \"HuΣeR\" feat.紫村 花澄"}},
        {31005, {"電子になりたい", "BEMANI Sound Team \"HuΣeR\""}},
        {31006, {"Riff//rain", "Rainy。"}},
        {31007, {"Vulnerability", "BEMANI Sound Team \"ZAQUVA\""}},
        {31008, {"Time Distortion pt.2(IIDX Edit)", "kors k vs BEMANI Sound Team \"setup\""}},
        {31009, {"frequent", "BEMANI Sound Team \"dj TAKA\""}},
        {31010, {"Cult Invitation", "BEMANI Sound Team \"謎の勢力\""}},
        {31011, {"Chemical Colours", "Blacklolita x BEMANI Sound Team \"Expander\""}},
        {31012, {"Speculation", "BEMANI Sound Team \"ZAQUVA\""}},
        {31013, {"めうめうぺったんたん！！ (ZAQUVA Remix)", "Remixed by BEMANI Sound Team \"ZAQUVA\""}},
        {31014, {"WaterCube Pf.(RX-Ver.S.P.L.)", "高田雅史"}},
        {31015, {"Sword of Vengeance", "sky_delta"}},
        {31016, {"Psychedelic Intelligence", "BEMANI Sound Team \"Sota Fujimori\""}},
        {31017, {"ポラリスノウタ", "ここなつ2.0"}},
        {31018, {"終焔のClaudia", "二代目朱雀"}},
        {31019, {"Get Higher", "BEMANI Sound Team \"劇団レコード\""}},
        {31020, {"Amethyst", "BlackY"}},
        {31021, {"アイドル", "Covered by BEMANI Sound Team \"HuΣeR × wac\" feat. 佐伯伊織"}},
        {31023, {"ちゅ、多様性。", "ano"}},
        {31024, {"酔いどれ知らず", "Remixed by SOUND HOLIC feat. Nana Takahashi"}},
        {31025, {"寝起きヤシの木", "Remixed by uno(IOSYS) feat. Chiyoko"}},
        {31026, {"Mukade", "kors k"}},
        {31027, {"Glitch N Ride", "Eagle"}},
        {31028, {"See You Again", "kors k & Numb'n'dub"}},
        {31029, {"winkle 2 winkle", "Ryu☆ ft.NU-KO"}},
        {31030, {"灼熱Beach Side Bunny (かめりあ's \"Summertime D'n'B\" Remix)", "Remixed by かめりあ"}},
        {31031, {"果たせぬ約束 ft. 小林マナ", "Xceon"}},
        {31032, {"COUNTING SHEEP ft. Kanae Asaba", "Xceon"}},
        {31033, {"Tripping Jumping", "Aikapin Prod. by uno & NiActivity"}},
        {31034, {"Out of Control", "CANVAS feat. Quimär"}},
        {31035, {"Echoes of Sunfall", "nora2r"}},
        {31036, {"今宵、ロマンス横丁。", "まろん feat. Rikotan"}},
        {31037, {"Stereo Beasts", "MK & RoughSketch"}},
        {31038, {"Bitter & Lucky", "DÉ DÉ MOUSE"}},
        {31039, {"Dahlia", "BlackY"}},
        {31040, {"Jumper", "Masayoshi Iimori"}},
        {31041, {"アタシ完全絶対正義ちゃん！", "Pizuya's Cell"}},
        {31042, {"シンデレラ", "Maozon feat. Nadia"}},
        {31043, {"摩天楼", "Julianne"}},
        {31044, {"惑星鉄道", "Snail's House"}},
        {31045, {"センチメンタル・サマー", "Nhato feat. Kanae Asaba & はるまき (from ボタニカルな暮らし。)"}},
        {31046, {"Demon March", "Nhato"}},
        {31047, {"Aeterna", "satella feat. Risa Yuzuki"}},
        {31048, {"Deep Sea Mystery", "Dirty Androids"}},
        {31049, {"Submerge Serenade", "lapix"}},
        {31050, {"INHERITANCE", "Zekk"}},
        {31051, {"MAXIMUM CHEAT GIRL", "かめりあ feat. ななひら"}},
        {31052, {"Resonant", "BEMANI Sound Team \"猫叉Master\" & かめりあ"}},
        {31053, {"れとりば！", "OSTER project feat. 月ノ輪乃愛"}},
        {31054, {"Vermilion Carol", "OSTER project"}},
        {31055, {"This Is Club Musik feat. 大久保紅葉", "REMO-CON"}},
        {31057, {"神様、つれない。", "中山真斗 feat. CHAN"}},
        {31058, {"GLORIOUS HAMMER", "AJURIKA"}},
        {31059, {"Level 5", "Yamato"}},
        {31060, {"ZEROIN ON THE LIGHT", "SOUND HOLIC Vs. ZYTOKINE feat. Nana Takahashi"}},
        {31061, {"電腦都市", "Blacklolita"}},
        {31062, {"夢縁", "xi feat. Risa Yuzuki"}},
        {31063, {"Shapeshifter", "Avans"}},
        {31064, {"Ghost Pulse", "crayvxn"}},
        {31065, {"閉塞的フレーション", "Pizuya's Cell VS BEMANI Sound Team \"dj TAKA\""}},
        {31066, {"GAME ON", "DJ Mass MAD Izm* feat.H14 of LEONAIR"}},
        {31067, {"DAZZLE ATTACK", "Yuta Imai"}},
        {31068, {"SOLAR ECLIPSE", "Yuta Imai Vs. BEMANI Sound Team \"Yvya\""}},
        {31069, {"TRIP THE DEEP", "Qlarabelle"}},
        {31070, {"夏風邪デスコ", "TORIENA"}},
        {31071, {"out of disk space", "TORIENA"}},
        {31072, {"ないないルーティン", "Len"}},
        {31073, {"My Sweet Bird?", "アオワイファイ feat.秋山雫"}},
        {31074, {"Too Late Snow", "movies (moimoi × Xceon × Dai.)"}},
        {31075, {"ACTØ", "モリモリあつし"}},
        {31076, {"GloriosA", "KARUT"}},
        {31077, {"流桜ノ門", "tokiwa"}},
        {31078, {"20XX", "COR!S"}},
        {31079, {"TITANIUM RIDERS", "DJ Shimamura"}},
        {31080, {"Just Gimme", "Maozon"}},
        {31081, {"Million Dollar", "Dirty Androids"}},
        {31083, {"Xb10r", "隣の庭は青い(庭師+Aoi)"}},
        {31084, {"Monkey Business", "kors k"}},
        {31085, {"Ambivalent Vermilia", "BEMANI Sound Team \"二代目朱雀 feat.朱雀\""}},
        {31086, {"《PL|RAYER》", "Blacklolita"}},
        {31087, {"電光", "Yuta Imai"}},
        {31088, {"Hat Surprise (Season 3)", "Hommarju"}},
        {31089, {"i-ii", "かめりあ"}},
        {31090, {"Red Determination", "RoughSketch"}},
        {31091, {"Sirius", "MK"}},
        {31092, {"Hard Breaker", "Nhato"}},
        {31093, {"Get Wicked", "Maozon"}},
        {31097, {"デビルじゃないもん", "Remixed by BlackY feat. Risa Yuzuki"}},
        {31098, {"可愛くてごめん", "Remixed by MK feat. 紫咲ほたる"}},
        {31099, {"フォニイ", "Remixed by Pizuya's Cell"}},
        {31100, {"唱", "Ado"}},
        {31101, {"勇者", "Remixed by OSTER project feat. そらこ"}},
        {31102, {"マーシャル・マキシマイザー", "Remixed by uno(IOSYS) feat. Chiyoko"}},
        {31103, {"雫", "あさき"}},
        {31104, {"squall", "猫叉Master+"}},
        {31105, {"BLAZING_LAZER", "brz1128"}},
        {31106, {"CODE:2", "HEXA"}},
        {31107, {"残像ニ繋ガレタ追憶ノHIDEAWAY", "SOUND HOLIC Vs. BEMANI Sound Team \"KE!JU\" feat. Nana Takahashi"}},
        {31108, {"PILGRIM", "crayvxn"}},
        {31109, {"NEEDLESS MY LOVE FOR YOU", "Pizuya's Cell"}},
        {31110, {"Akatsuki", "PRIDASK"}},
        {31111, {"So What", "PRIDASK"}},
        {31112, {"ラビットホール", "DECO*27"}},
        {31113, {"愛包ダンスホール", "HIMEHINA"}},
        {31115, {"Seven Times Four", "Hommarju"}},
        {31116, {"T.R.O.L.L.", "Yuta Imai"}},
        {31117, {"The Onlyonez", "RoughSketch"}},
        {31118, {"リメンバーリメンバー", "rino & m@sumi from plastic penguin"}},
        {31119, {"未完成ノ蒸氣驅動乙女", "U1 overground"}},
        {32000, {"スパークリング☆彡ハイパーチューン！！", "Machico"}},
        {32001, {"ADAMANT", "BEMANI Sound Team \"L.E.D.-G\""}},
        {32002, {"スキッテイエェエエェ!!!!", "cosMo＠暴走P & BEMANI Sound Team \"L.E.D.-G\""}},
        {32003, {"IN BETWEEN", "BEMANI Sound Team \"L.E.D.-G\" feat. Mayumi Morinaga"}},
        {32004, {"KOTONOHA ft. Kotoha", "EmoCosine × BEMANI Sound Team \"HuΣeR\""}},
        {32005, {"NOIXIA", "BEMANI Sound Team \"HuΣeR\""}},
        {32006, {"uən", "少年ラジオ"}},
        {32007, {"SISYPHUS", "BEMANI Sound Team \"Paoon\""}},
        {32008, {"天使のカンタータ -Cantata of Angels-", "BEMANI Sound Team \"Cuvelia\""}},
        {32009, {"destination", "One Round Rabbits"}},
        {32010, {"Pinky Happy Crazy", "BEMANI Sound Team \"Risk Junk\""}},
        {32011, {"Digital Radiance", "BEMANI Sound Team \"Sota Fujimori\" feat. S.B.Z."}},
        {32012, {"lowercase lifetime", "BEMANI Sound Team \"ZAQUVA\""}},
        {32013, {"Without Heaven", "BEMANI Sound Team \"ZAQUVA\""}},
        {32014, {"最強頂戴girl♡", "BEMANI Sound Team \"TATSUYA\" feat. ななひら"}},
        {32015, {"ハルイロメロディー", "月乃 ＆ BEMANI Sound Team \"劇団レコード\""}},
        {32016, {"Arcanos", "DJ Totoriott"}},
        {32017, {"Slumber☆Party", "BEMANI Sound Team \"めめめ\""}},
        {32019, {"きゅうくらりん", "いよわ"}},
        {32020, {"Galaxy Collapse", "BEMANI Sound Team \"めめめ\""}},
        {32021, {"hora de verdad", "Vandalusia改"}},
        {32022, {"PERFECT HUMAN", "Remixed by Ryu☆ feat. BEMANI Sound Team \"PON\""}},
        {32023, {"MVP", "PRIDASK"}},
        {32024, {"Roar of Chronos", "BEMANI Sound Team \"KE!JU\""}},
        {32025, {"爆ぜりゃんせ", "敦姫"}},
        {32026, {"Bring The Fire", "kors k"}},
        {32027, {"Bang-Boo Bumble", "二代目白虎"}},
        {32028, {"u gotta beat", "KARUT"}},
        {32029, {"Mighty Cutie", "KARUT"}},
        {32030, {"everlastingeuphoria:", "crayvxn"}},
        {32031, {"Chasing After YOU ～夢の欠片～ ft. 小林マナ", "Xceon"}},
        {32032, {"Stargazing Trip ～星 探す旅～ ft. 小林マナ", "Xceon"}},
        {32033, {"Vibing! Shake it!", "らっぷびと Prod. by RoughSketch & NUE"}},
        {32034, {"Flämingo", "CANVAS feat. Quimär"}},
        {32035, {"Drop Syndicate", "Seventhrun × nora2r"}},
        {32036, {"1116", "BEMANI Sound Team \"Dustup\""}},
        {32037, {"Lycoris", "BEMANI Sound Team \"HuΣeR\" feat.Fernweh"}},
        {32038, {"Aqvion", "lapix"}},
        {32039, {"FERMI♡PARADOX", "BlackY feat. Risa Yuzuki"}},
        {32040, {"Space In Time", "Masayoshi Iimori"}},
        {32041, {"消極的セツナイズム", "Pizuya's Cell"}},
        {32042, {"Constellation", "Maozon"}},
        {32043, {"ELYSIUM", "Snail's House"}},
        {32044, {"ＰＡＳＴＥＬＩＳＭ", "Snail's House"}},
        {32045, {"Dreamship", "Nhato feat. Kanae Asaba"}},
        {32046, {"きみのせかい", "Nhato"}},
        {32047, {"Eleanor", "satella feat. nayuta"}},
        {32048, {"Fiery Stallion", "Dirty Androids"}},
        {32049, {"オッド♡ラヴィ", "lapix feat. PANXI"}},
        {32050, {"PIT A PAT", "Zekk"}},
        {32051, {"MARLIN", "Zekk"}},
        {32052, {"God Mind", "Tatsunoshin"}},
        {32053, {"DIVINE JUDGEMENT", "OSTER project"}},
        {32054, {"Shirdal", "Dirty Androids"}},
        {32055, {"Mid-Corner (Magic Maker)", "REMO-CON"}},
        {32056, {"Show Me All Your Love", "Hommarju"}},
        {32057, {"弾幕信仰", "豚乙女×BEMANI Sound Team \"PON\""}},
        {32058, {"EX-MASSIVE FIGHTER", "BEMANI Sound Team \"L.E.D.-G\""}},
        {32059, {"無双", "SOUND HOLIC Vs. VENUS feat. Nana Takahashi"}},
        {32060, {"SUPER HEROINE!!", "Amateras Records vs BEMANI Sound Team \"TATSUYA\" feat. miko"}},
        {32061, {"FlyAway", "Blacklolita"}},
        {32062, {"Satellite Burst", "xi"}},
        {32063, {"ロマンシングエスケープ", "ここなつ2.0"}},
        {32064, {"アラビアン ハイパー ナイト", "BEMANI Sound Team \"マックス ステロイ度！\""}},
        {32065, {"Butterfly Twist", "Yooh"}},
        {32066, {"灼熱 Lost Summer Dayz", "DJ Mass MAD Izm* feat.すみはね"}},
        {32067, {"RAVE SYNDROME", "Yuta Imai"}},
        {32068, {"SμG@R RU$#", "Yuta Imai"}},
        {32069, {"TECHNO RUMBLE", "Qlarabelle"}},
        {32070, {"断罪の一花", "Len feat.mochari"}},
        {32071, {"get set mind", "TORIENA"}},
        {32072, {"ドリムチウ", "TORIENA"}},
        {32073, {"PopなEDEN", "YASUHIRO(康寛) feat.橘田ほのか"}},
        {32074, {"CHAOTIC SUNBIRD", "Tanchiky"}},
        {32075, {"Raspberry Potion (feat.あれたん♡ & ぎゃるのしん☆)", "Tatsunoshin & 藍良あれれ"}},
        {32076, {"Here We Go Now", "Whac-A-Me"}},
        {32077, {"Secret Rouge", "ハレトキドキ"}},
        {32078, {"飴玉", "CYNHN"}},
        {32079, {"我ら完全無敵のアイドル!!", "B小町"}},
        {32080, {"えだまめカレークッキング", "OSTER project feat. ずんだもん ＆ 春日部つむぎ"}},
        {32081, {"ゲシュタルト", "花譜"}},
        {32082, {"ビビデバ", "星街すいせい"}},
        {32083, {"メズマライザー", "サツキ feat.初音ミク・重音テトSV"}},
        {32084, {"Bling-Bang-Bang-Born", "Covered by uno(IOSYS) feat. Fra"}},
        {32085, {"イガク", "原口沙輔 feat.重音テト"}},
        {32093, {"Lightspeed", "Tanukichi"}},
        {32094, {"ファイナルレター", "かねこちはる"}},
        {32095, {"COSMIC V3LOCITY", "BEMANI Sound Team \"Coyaan & KE!JU & ZAQUVA\""}},
        {32096, {"ドーナツホール 2024", "ハチ"}},
        {32097, {"ハオ", "DECO*27"}},
        {32098, {"オブソミート", "サツキ feat.初音ミク、重音テト"}},
        {32099, {"Skratch Education Lv-1", "DJ Mass MAD Izm*"}},
        {32100, {"Uaigh Gealaí", "かめりあ"}},
        {32101, {"進捗ダメダメです", "GYARI feat.宮舞モカ、弦巻マキ"}},
        {32102, {"ギャ・ギャ・ギャ・ギャラクシー！", "つきみぐー、"}},
        {32103, {"エクスプロウル", "晴いちばん"}},
        {32104, {"覚悟せよ！エンタンメ～ン ～より身の切り売り自暴自棄版～", "マキシウキョウ"}},
        {32105, {"朱と碧のランページ", "NU-KO"}},
        {32106, {"Plea Per Phase", "Feryquitous"}},
        {32107, {"Cross Fire", "Hommarju vs RoughSketch"}},
        {32108, {"XHRONOXAPSULΞ", "Silentroom"}},
        {32109, {"EYE OF THE HEAVEN", "BEMANI Sound Team \"U1-ASAMi\""}},
        {32110, {"Plazma", "米津玄師"}},
        {32111, {"キスキツネ", "HIMEHINA"}},
        {32112, {"Good Looking", "JAKAZiD"}},
        {33000, {"ビビッド ☆+*。キラキライム", "Machico"}},
        {33001, {"かわいいだけじゃだめですか？", "Remixed by BEMANI Sound Team \"L.E.D.-G\" feat. 佐伯伊織"}},
        {33008, {"Countdown to Heaven or Hell", "BEMANI Sound Team \"dj TAKA\""}},
        {33013, {"デラむぅのでらっくす☆どり～むぅ", "デラむぅと BEMANI Sound Team “TATSUYA”お兄さん"}},
        {33015, {"鏡像都市", "BEMANI Sound Team \"劇団レコード\" feat.T4K"}},
        {33016, {"A Certified Rave Moment", "BEMANI Sound Team \"めめめ\""}},
        {33017, {"Substance", "BEMANI Sound Team \"めめめ\""}},
        {33020, {"夏色のセレナーデ", "BEMANI Sound Team \"KE!JU\""}},
        {33021, {"From Human Blood", "BEMANI Sound Team \"U1-ASAMi\""}},
        {33022, {"Space Battleship S4TØ", "BEMANI Sound Team \"Captain Sonic\""}},
        {33024, {"Makin' It", "DJ RENA "}},
        {33028, {"Regina vespaE", "KARUT"}},
        {33031, {"JUST SYNC ft.Kanae Asaba", "Xceon"}},
        {33033, {"ベラ・ベ・カラベラ", "Fra Prod. by RoughSketch"}},
        {33035, {"MOCHIMOCHI DREAMIN!!", "nora2r × まろん feat. 和鳴るせ"}},
        {33038, {"閃と雷管とロープ", "めと（Metomate）"}},
        {33039, {"Vitamin", "BlackY"}},
        {33040, {"RALLY '25", "Masayoshi Iimori"}},
        {33041, {"煉獄コンフィチュール", "Pizuya's Cell"}},
        {33043, {"月下繚乱", "Julianne"}},
        {33045, {"Bang Bang Dance", "Nhato"}},
        {33047, {"Memoria Obscura", "satella"}},
        {33049, {"PALETTE", "lapix feat. 奈良ひより"}},
        {33050, {"Disco Killer Music Lover", "Zekk"}},
        {33052, {"Fashion Fruit", "Tatsunoshin x Aira Arere"}},
        {33061, {"ιgniЯRuina", "xi feat. Risa Yuzuki"}},
        {33062, {"SnapSkipSpark", "Feryquitous"}},
        {33064, {"AGETEKE ONDO", "暁Records"}},
        {33067, {"SPLASH!!!!!!!!!", "Yuta Imai"}},
        {33071, {"それが、ボクの使命～レスキュー隊長 メンキュー～", "TORIENA"}},
        {33073, {"2 Be Continued", "打打だいず"}},
        {33074, {"Catch ya Getcha!", "Tanchiky"}},
        {33075, {"百恋ラブラスター", "irucaice feat. ななひら"}},
        {33077, {"SHINING☆DANCE", "ハレトキドキ"}},
        {33078, {"Shooting Star", "ReGLOSS"}},
        {33081, {"でんぱ どりる わんにゃー☆三", "キノシタ feat. 重音テト"}},
        {33082, {"LEMON MELON COOKIE", "TAK feat.初音ミク"}},
        {33083, {"もんめためたもん", "OSTER project feat. ずんだもん ＆ 四国めたん"}},
        {33084, {"バブリン", "HIMEHINA"}},
        {33085, {"Caramel Pain", "星街すいせい"}},
        {33086, {"Nyan Nyan University ", "Aice room"}},
        {33333, {"TUTORIAL", "TUTORIAL"}},
    };
}
