#pragma once
#include <string>
#include <unordered_map>

// Auto-generated MUSYNX song database

struct MuSynxSongInfo {
    std::string title;
    std::string composer;
    int bpm;
};

inline std::unordered_map<std::string, MuSynxSongInfo> getMuSynxSongDB() {
    return {
        {"13vis", {"13/VIS", "ETIA.", 129}},
        {"2anyFirst", {"2anyFirst", "Sobrem", 158}},
        {"404", {"404 Not Found", "Kide", 120}},
        {"66CCFF", {"66CCFF", "杉田朗", 113}},
        {"8BITO", {"8BITO", "希望索任合资", 121}},
        {"8bitAdventurer", {"8bit Adventurer", "Lime", 118}},
        {"8sec", {"八秒之语", "PoKeR", 165}},
        {"8thPlanet", {"8th Planet [Re-Search]", "P4koo", 116}},
        {"AliceM", {"Alice in Misanthrope -厭世アリス-", "LeaF", 145}},
        {"AllieStars", {"Allie Stars", "Hazel-D", 138}},
        {"ArroganT", {"ArroganT", "Kide", 120}},
        {"Artificialintelligence", {"Artificial Intelligence", "Street", 160}},
        {"Asterios", {"Asterios -Re-Entry-", "ATAS (Remixed by Nasch)", 120}},
        {"AstralInjection", {"Astral Injection", "Xacla", 148}},
        {"Aurora", {"Aurora", "Lime", 136}},
        {"Awakeninruins", {"Awaken In Ruins", "Supa7onyz", 138}},
        {"Bibicheart", {"BiBiC Heart", "MYUKKE.", 133}},
        {"Binarystar", {"Binary Star", "透音 feat. 白黒あんこ", 120}},
        {"Bisoncharge", {"Bison Charge(MUSYNX Update)", "梅干茶漬け", 107}},
        {"BokugaMitaSekai", {"僕が見た世界", "Kankitsu feat.Salita", 120}},
        {"BoxelAdventure", {"Boxel Adventure", "7mai", 122}},
        {"BrainCrash", {"Brain Crash", "rider", 126}},
        {"Brightredhertz", {"Bright red hertz", "影虎。", 131}},
        {"ButterflyDance", {"Butterfly Dance", "XinG", 111}},
        {"CNparents", {"中国式家长[高考前夕]", "minipanda", 156}},
        {"CO5M1CR4ILR0AD", {"CO5M1C R4ILR0AD", "kanone", 120}},
        {"Cantitbeture", {"Can't it be true", "Zris  feat.Kri", 134}},
        {"Chaoyuanjvlianjie", {"超远距连接", "小野道OvO", 232}},
        {"CityNightComedy", {"City Night Comedy", "ILso_machine", 126}},
        {"Crossdestination", {"Cross†Destination", "HyuN", 117}},
        {"CrushAlcohol", {"Crush alcohol", "shadow_bling", 156}},
        {"CrushBeta", {"Crush BETA", "shadow_bling", 120}},
        {"Dongfengdaohe", {"東風稻荷", "WABI", 114}},
        {"Dontneveraround", {"Don't Never Around", "HAMA", 119}},
        {"Dujiao", {"独角", "UnicornPhantom", 181}},
        {"ESM", {"ENERGY SYNERGY MATRIX", "Tanchiky", 124}},
        {"Electric_Emotion", {"Electric Emotion", "nmk feat. 橘花音", 118}},
        {"Emptiness", {"Emptiness", "Xect.", 120}},
        {"Endruid", {"ENDRUiD", "MYUKKE.", 135}},
        {"Eschatology", {"Eschatology", "Tatsh,Scarlette", 151}},
        {"Euphoria", {"Euphoria(MUSYNX EDIT.)", "PIKASONIC & Tatsunoshin", 156}},
        {"Flammable", {"Flammable", "Sho Fish", 122}},
        {"Foreverloved", {"Forever loved", "NCES", 164}},
        {"Fourleafclover", {"Four leaf clover", "7mai", 130}},
        {"GOODRAGE", {"GOODRAGE", "EBIMAYO", 119}},
        {"GOODWORLD", {"GOODWORLD", "EBIMAYO", 120}},
        {"Giselle", {"Giselle", "Widowmaker", 139}},
        {"Glazedcolor", {"Glazed Color", "Relemo", 150}},
        {"Gooddream", {"做个好梦", "", 160}},
        {"Gots", {"The Guardians Of The Sun", "RiraN", 150}},
        {"GrowthCall", {"Growth Call", "siqlo", 168}},
        {"Hailnpray", {"Hail'n'Pray", "Blacklolita", 123}},
        {"Hatencode583", {"HATEN CODE 583", "MYUKKE.", 138}},
        {"Hesuige", {"贺岁歌", "AiSS", 120}},
        {"Huanglaobing", {"<color=yellow>黄</color>老饼梦<color=yellow>游</color>惊奇", "wolfnight狼夜", 130}},
        {"Huaxiwang", {"花たちに希望を", "Sound piercer", 170}},
        {"IKAROS", {"IKAROS", "ETIA. feat. Jenga", 123}},
        {"Invertedworld", {"Inverted World", "ARForest", 131}},
        {"InvisibleChaos", {"Invisible Chaos", "Rainword", 134}},
        {"Kingform", {"KiNG FORM -XIII- (2023 Update)", "Reku Mochizuki", 144}},
        {"Kirakiranoelstory", {"Kirakira Noel Story!!", "Reku Mochizuki", 136}},
        {"Lantinid", {"Lantinid", "ARForest", 116}},
        {"Lazuladia", {"Lazuladia", "Reku Mochizuki", 133}},
        {"Lemonade", {"Lemonade", "7mai", 120}},
        {"Lockdown", {"Lockdown（musynx edit.）", "PIKASONIC & Tatsunoshin", 152}},
        {"Luxinauz", {"Luxinauz", "R.Solidor", 150}},
        {"MARENOL", {"MARENOL", "LeaF", 120}},
        {"Maholova", {"Maholova", "aran", 140}},
        {"Megastructure", {"Megastructure", "technoplanet", 146}},
        {"MindDisorder", {"Mind Disorder", "Alkome", 135}},
        {"MiraiMiracle", {"Mirai Miracle", "GhostFinal", 120}},
        {"Mofashaonv", {"魔法少女になるしかねぇ", "ねこみりん feat.小宮真央", 135}},
        {"Moonlight", {"moon light", "ginkiha", 131}},
        {"Nwad", {"[NWAD]", "Knighthood", 159}},
        {"Oukaranman", {"日本式硬核 - Oukaranman", "ETIA.", 127}},
        {"Paradigmshift", {"Paradigm Shift", "モリモリあつし", 114}},
        {"Phonon", {"Phonon", "Sho Fish", 113}},
        {"Polacro", {"Polacro", "隣の庭は青い(庭師+Aoi)", 148}},
        {"Poppy", {"Poppy", "Columba(Daily vs. Roon_kun)", 142}},
        {"Provison", {"Provison", "Connexio", 141}},
        {"Pupa", {"PUPA", "モリモリあつし", 124}},
        {"R2TY", {"Run2 Run To You!!", "梅干茶渍け", 116}},
        {"RIP", {"『R.I.P.』", "eicateve", 142}},
        {"Random", {"Random", "Sobrem × Silentroom", 136}},
        {"Rehain", {"Regain", "projectG", 134}},
        {"ReviXy", {"ReviXy", "ikaruga_nex", 159}},
        {"Revivalofkalpa", {"Revival of Kalpa", "Scarlette", 180}},
        {"SS", {"Signal Scream", "ZOMiG", 120}},
        {"Saintelmo", {"Saintelmo", "Aoi", 132}},
        {"Shechu", {"人里に下ったアタイがいつの間にか社畜になっていた件", "ねこみりん + nora2r feat.小宮真央", 131}},
        {"Shizuku", {"Shizuku (ft. NEONA & KOTONOHOUSE)", "PIKASONIC & Tatsunoshin", 175}},
        {"Shootingstars", {"Shooting☆Stars", "DJ Genki", 129}},
        {"Shuangsheng", {"双生のネビュラ", "S9ryne Feat. Sennzai", 196}},
        {"SilenceToFreeze", {"Silence To Freeze", "NceS", 160}},
        {"Skyfragment", {"Sky Fragment", "X-END-", 137}},
        {"SpookyMelodicNight", {"Spooky Melodic Night", "Blacklolita", 126}},
        {"Spookymummyparty", {"Spooky Mummy Party", "Jun Kuroda", 150}},
        {"Steelcorebullet", {"Steel Core Bullet", "Sho Fish", 115}},
        {"SubmergeinColor", {"Submerge in Color", "Glacia Sound Team“ILusMin\"", 129}},
        {"Supernovaproject", {"Super Nova Project", "shadow_bling", 185}},
        {"TC4U", {"This Club is Not 4 U", "EmoCo", 135}},
        {"TLP", {"The Last Page", "ARForest", 120}},
        {"TepicTepoch", {"Tepic Tepoch", "technoplanet", 192}},
        {"Thedaywebecomefamily", {"The Day We Become Family", "VeetaCrush & S9ryne<nk.>", 230}},
        {"Thelastpage", {"The Last Page", "ARForest", 141}},
        {"Together", {"Together", "ραη", 110}},
        {"Tracingshadow", {"tracing shadow", "S9ryne", 152}},
        {"Trickortreat", {"不给糖就捣乱", "ikz_茶壶", 176}},
        {"UntroddenMorn", {"Untrodden Morn", "Silentroom", 158}},
        {"Upshift", {"Upshift", "Iriss-Frantzz", 141}},
        {"Vantablack", {"Vantablack", "siqlo", 150}},
        {"Voyager", {"8bit Voyager", "Lime", 137}},
        {"Wishuponthepolarstar", {"Wish Upon The Polar Star", "Jun Kuroda", 148}},
        {"Wormholem", {"WormholeM", "kry.exe", 120}},
        {"Wuxianjvchang", {"无限剧场", "S9ryne & VeetaCrush", 195}},
        {"Xenolith", {"Xenolith", "Tatsh", 137}},
        {"Xigns", {"Xigns", "Reku Mochizuki", 138}},
        {"YInMnBlue", {"YInMn Blue", "siqlo", 129}},
        {"Yeyingwu", {"夜桜舞う時から", "S9ryne Feat. 幽舞越山+祈Inory", 132}},
        {"Yeyuehua", {"夜月花", "Zuxin", 126}},
        {"Yuexiayingtianguo", {"月下桜天国", "Zuxin with Utsuro", 132}},
        {"Zheichour", {"Zheichour", "R.Solidor", 155}},
        {"Zhonghuashaonvzhong", {"中华少女·终", "純白p", 256}},
        {"africa", {"Africa", "ETIA.", 139}},
        {"afs4", {"ANGER FORCE - STAGE 4 -", "", 97}},
        {"afterdawn", {"After Dawn", "S9ryne", 138}},
        {"altros", {"Altros", "ARForest", 115}},
        {"annihilator", {"Annihilator", "Lunatic Sounds", 169}},
        {"athaza", {"ATHAZA", "LeaF", 161}},
        {"auburnHalo", {"Auburn Halo", "Arctures", 157}},
        {"azrael", {"AzraEL", "Enoch", 120}},
        {"b612", {"B612", "litmus*", 106}},
        {"blitzKreig", {"BlitzKrieg", "Lunatic Sounds", 103}},
        {"bloodyMary", {"血腥玛丽", "花之祭P", 110}},
        {"boysFriends", {"Boys & Friends", "潜移默化P", 120}},
        {"brainPower", {"Brain Power", "NOMA", 167}},
        {"bt", {"Bass telekinesis", "Haloweak", 131}},
        {"bth", {"Beyond The Horizon", "M2U", 129}},
        {"btt", {"BOUNCE THE TECH", "Sound piercer vs. Iriss", 116}},
        {"burn", {"Burn", "NceS", 134}},
        {"buybuybuy", {"我要买买买", "iKz", 125}},
        {"cancan", {"Cancan-Orpheus", "Jacques Offenbach", 129}},
        {"canonInD", {"Canon in D", "Pachelbel", 190}},
        {"celestial", {"Celestial Axes", "nmk", 124}},
        {"chivalric", {"Chivalric", "shadow_bling", 123}},
        {"chronomia", {"Chronomia", "Lime", 146}},
        {"cipher", {"Cipher : /2&//<|0", "Tetrajectory feat. Ctymax", 152}},
        {"cmb", {"Call me baby", "Utae & oCau", 112}},
        {"cn", {"Confession", "Haloweak&G.K", 120}},
        {"co5m1c", {"CO5M1C R4ILR0AD", "kanone", 136}},
        {"colorfuldays", {"Colorful Days♪", "P4koo feat. つゆり花鈴", 98}},
        {"comeForYou", {"为你而来", "希望索任合资", 120}},
        {"connect", {"CONNECT-心的连接-", "阿良良木健", 127}},
        {"cordPlayer", {"Cord Player", "Zris", 124}},
        {"czxy", {"天朝从众效应", "绛舞乱丸", 134}},
        {"dataerr0r", {"Data Err0r", "Lunatic Sounds", 121}},
        {"delusion1", {"妄想症一重加害", "DELA", 120}},
        {"delusion2", {"妄想症二重变革", "DELA", 120}},
        {"delusion3", {"妄想症三重爱恋", "DELA", 120}},
        {"delusion4", {"妄想症四重罪孽", "DELA", 120}},
        {"delusion5", {"妄想症五重空洞", "DELA", 120}},
        {"delusion6", {"妄想症六重不忠", "DELA", 120}},
        {"delusion7", {"妄想症七重痼病", "DELA", 120}},
        {"delusion8", {"妄想症八重回归", "DELA", 120}},
        {"delusion9", {"妄想症九重现实", "DELA", 120}},
        {"diamondSmile", {"Diamond Smile", "YOU feat. nayuta", 159}},
        {"diao", {"你真的好弔", "黒白P", 125}},
        {"dionysia", {"εν.στει Διον.σια", "半璧&LBG", 146}},
        {"doomsdayDisco", {"末日Disco", "阿良良木健&oCaU", 170}},
        {"doppelganger", {"Doppelganger", "LeaF", 146}},
        {"efth", {"Escape From The Heart", "Cre-sc3NT", 120}},
        {"enchantedlove", {"enchanted love", "linear ring", 128}},
        {"energytrixxx", {"energy trixxx", "KAH", 139}},
        {"epilogue", {"epilogue", "VeetaCrush", 117}},
        {"evanescent", {"Evanescent", "LeaF", 127}},
        {"fallinfallin", {"fallin' fallin'", "INFX, Ella Jung, Limpid", 152}},
        {"farAway", {"Far Away", "P4koo", 134}},
        {"fbzx", {"异样的风暴中心", "杉田朗", 153}},
        {"finalDash", {"Final Dash", "MUE", 90}},
        {"findMe", {"Find Me", "Lunatic Sounds", 113}},
        {"flashdance", {"Flashdance", "litmus*", 121}},
        {"fnz", {"腐女子的恋爱理论", "潜移默化P", 120}},
        {"fos", {"Flurry Of Sakura", "GhostFinal", 90}},
        {"futureDive", {"Future Dive", "Lunatic Sounds", 111}},
        {"futureGoal", {"高考恋爱100天[未来的志愿书]", "WING翼", 114}},
        {"galaxyStriker", {"Galaxy Striker", "M2U", 91}},
        {"gameBoy", {"GAMEBOY", "Silentroom", 193}},
        {"gaobai", {"告白・告别(MUSYNX Edit.)", "Greetea", 170}},
        {"gaobaibms", {"告白・告别(BMS Edit.)", "Greetea feat. ninnikuu", 170}},
        {"gavotteInD", {"Gavotte in D", "François Joseph Gossec", 121}},
        {"ginkgo", {"Tales of Ginkgo", "Zris", 134}},
        {"gk", {"我要挂科了", "跳蝻", 113}},
        {"goodBounce", {"GOODBOUNCE(MUSYNC EDIT)", "EBIMAYO", 130}},
        {"goodMen", {"GOODMEN", "EBIMAYO", 127}},
        {"goodTek", {"GOODTEK", "EBIMAYO", 123}},
        {"goodlife", {"Good Life", "litmus*", 142}},
        {"goodworld_HD", {"GOODWORLD (Hardstyle Remix)", "EBIMAYO", 120}},
        {"gothiqueResonance", {"Gothique", "P4koo", 120}},
        {"haitangxian", {"海棠仙", "純白P", 116}},
        {"healthylife", {"Healthy Life", "technoplanet", 151}},
        {"hellohalley", {"Hello Halley", "小野道", 174}},
        {"hiddenending", {"Hidden Ending", "ARForest", 133}},
        {"hope", {"OPUS地球计划[Hope]", "Triodust", 132}},
        {"housePlan", {"HOUSEPLAN", "houseplan!", 120}},
        {"houseplan", {"HOUSEPLAN", "houseplan!", 134}},
        {"huachenlvxing", {"化尘旅行", "Tuno桐音", 139}},
        {"humoresque", {"幽默曲", "Antonín Leopold Dvořák", 115}},
        {"huoxingtuzi", {"惑星ラビット", "Yunomi feat. TORIENA", 157}},
        {"ic", {"Infinite Collapse", "S9ryne", 121}},
        {"icey", {"ICEY", "Ziqi Liu", 190}},
        {"ilu", {"Love Wallet", "阿良良木健&oCaU", 158}},
        {"implexrough", {"Implexrough", "Silentroom × mommy", 131}},
        {"indoor", {"インドア系ならトラックメイカー", "Yunomi & nicamoq", 198}},
        {"infinity", {"INFINITY", "Lunatic Sounds", 139}},
        {"infomorph", {"Infomorph", "ETIA. feat. Jenga", 138}},
        {"iou", {"I LOVE U", "阿良良木健", 124}},
        {"jingtaoluori", {"神州电音[惊涛落日]", "磨蹭_platix_zhang&克艾尔西", 170}},
        {"jjbsy", {"九九八十一", "乌龟", 187}},
        {"journey", {"JOURNEY", "战场原妖精", 168}},
        {"jpx", {"键盘侠的斗争哲学", "绛舞乱丸", 125}},
        {"jq", {"矫情", "绛舞乱丸", 124}},
        {"keepOn", {"Keep oN!", "雨漏りP", 130}},
        {"keepYourPassion", {"Keep Your Passion", "Lunatic Sounds", 135}},
        {"kerberos", {"Kerberos", "Zris", 125}},
        {"kira", {"キラ", "Luna Safari", 96}},
        {"koi", {"鲤[一河上下两世界]", "Zeta", 125}},
        {"lalala", {"LALALA Refrain", "ZOMiG", 153}},
        {"lastMessage", {"LAST MESSAGE", "希望索任合资", 120}},
        {"lazhuren", {"蜡烛人[摇曳]", "Zeta", 93}},
        {"lch", {"落尘寰", "LBG", 180}},
        {"legendary", {"Legendary", "Enoch", 130}},
        {"legendaryPT2", {"Legendary PT.2", "Enoch", 159}},
        {"leyuan", {"樂園－Atlantis－", "Evalia", 120}},
        {"lifeisjourney", {"Life is Journey", "Junk", 178}},
        {"lifeispiano", {"Life is PIANO", "Junk", 125}},
        {"lilithAmbivalenceLovers", {"Lilith ambivalence lovers", "ikaruga_nex", 154}},
        {"liubing", {"溜冰圆舞曲", "Emil Waldteufel", 134}},
        {"liuguang", {"流光织雨[三色绘恋S OP]", "丸山公詳(project  lights)", 112}},
        {"liveyourownlife", {"Live Your Own Life", "Junk", 162}},
        {"loveInfectionStem", {"Love Infection", "Pointless", 144}},
        {"luobi", {"兔子罗比", "Eurico", 130}},
        {"luotianyu", {"洛天鱼", "杉田朗", 133}},
        {"lyrith", {"Lyrith - 迷宮リリス -", "ユメミド", 147}},
        {"mRabbit", {"兔子先生", "小桦啊小桦", 155}},
        {"makeitfunkynow", {"MAKE IT FUNKY NOW", "DOT96", 121}},
        {"makesMeWonder", {"Makes Me Wonder", "P4koo", 149}},
        {"metatron", {"Metatron -Re:Birth-", "OptiU", 120}},
        {"mfcn", {"魔法厨娘", "希望索任合资", 134}},
        {"monochromecity", {"Monochrome City", "technoplanet", 148}},
        {"moonWestRiver", {"月西江", "solpie", 168}},
        {"mopemope", {"もぺもぺ", "LeaF", 112}},
        {"motuo", {"骑上我心爱的小摩托", "静sir", 120}},
        {"nekoPara", {"ネコぱら[タイヨウパラダイス]", "水城新人", 125}},
        {"nekostep", {"ねこちゃんステップ", "P4koo feat. re_you", 131}},
        {"news0", {"https://store.playstation.com/#!/zh-hans-hk/cid=HP2210-CUSA09356_00-2017080700000000", "", 120}},
        {"nextFar", {"下一个远方", "战场原妖精", 145}},
        {"nickOfTime", {"Nick of Time", "P4koo", 135}},
        {"nini", {"ニニ", "テヅカ × Qayo", 140}},
        {"nlqq", {"逆浪千秋", "乌龟", 159}},
        {"nobodyKnows", {"Nobody Knows", "ETIA. feat. Sennzai", 146}},
        {"normalDisco", {"普通DISCO(三无)", "普通的ilem", 120}},
        {"normalDiscoPT", {"普通DISCO", "普通的ilem", 125}},
        {"normalPersion", {"做一个默默无闻的普通人", "黒白P", 120}},
        {"nowisthetime", {"Now Is The Time, Do It", "Roy Mikelate", 132}},
        {"nulctrl", {"NULCTRL", "Silentroom", 148}},
        {"onandon", {"On And On!!", "ETIA. feat. Jenga", 120}},
        {"oneDream", {"一梦千朝", "乌龟", 115}},
        {"oneWayStreet", {"One Way Street", "siqlo", 143}},
        {"opia", {"opia -awakened- (MUSYNC edit)", "rN", 155}},
        {"orientalShade", {"Oriental Shade", "seibin", 141}},
        {"otherText", {"otherText", "", 120}},
        {"otogi", {"おとぎ話の日々", "Yunomi feat. 熊子", 162}},
        {"pancakeIsLove", {"MUSE DASH[Pancake Is Love]", "3R2", 114}},
        {"panxing", {"蹒行手记", "Wing翼", 150}},
        {"pinklemon", {"粉色柠檬", "战场原妖精", 120}},
        {"platina", {"Platina", "Memme", 132}},
        {"pp", {"纸飞机", "GhostFinal", 127}},
        {"qdldq", {"齐德隆咚呛", "跳蝻", 98}},
        {"qesia", {"Qesia", "ARForest", 124}},
        {"ql", {"Quantum Labyrinth", "Haloweak", 142}},
        {"qnsps", {"千年食谱颂", "H.K.君", 166}},
        {"quia", {"quia desolatio", "rN", 153}},
        {"qwyp", {"欠我一炮", "潜移默化P", 120}},
        {"rain", {"Rain", "technoplanet", 140}},
        {"redDust", {"呓语红尘", "乌龟", 134}},
        {"redhat", {"小红帽的一天", "Wing翼", 139}},
        {"rpg", {"一天一炮的愉悦", "鸣子兔", 114}},
        {"sakasama", {"サカサマの空に在ったのは", "qfeileadh", 138}},
        {"sakuraFubuki", {"Sakura Fubuki", "Street", 116}},
        {"sanse", {"三色绘恋[三色绘恋 OP]", "丸山公詳(project  lights)", 102}},
        {"seattle", {"Seattle物语Ⅱ", "Ddickky", 122}},
        {"shiyu", {"恋时雨[三色绘恋S ED]", "丸山公詳(project  lights)", 95}},
        {"shskies", {"Shattered Skies", "ATAS", 118}},
        {"silverTown", {"Silver Town", "Memme", 124}},
        {"smile", {"smiling", "Lime", 157}},
        {"snqx", {"少女前线[梦与血的赞美诗]", "战场原妖精", 120}},
        {"songshu", {"松鼠魔法祭", "小旭PRO-Joeway", 136}},
        {"spica", {"スピカ", "qfeileadh", 121}},
        {"sqsj", {"三千世界鸦杀尽", "花之祭P", 140}},
        {"srhz", {"三人合奏歌", "花之祭P", 131}},
        {"ssqj", {"苏三起解", "", 125}},
        {"starSky1", {"那片小小的星空", "月代 彩", 145}},
        {"starSkyNeptune", {"星空NEPTUNE", "PoKeR", 150}},
        {"stardustDebris", {"星屑碎片", "花之祭P", 125}},
        {"stargazer", {"观星者", "战场原妖精", 120}},
        {"starlightFactory", {"Starlight Factory", "ATAS", 132}},
        {"sterelogue", {"Sterelogue", "VeetaCrush", 142}},
        {"stormChaser", {"Storm Chaser", "KIEN", 135}},
        {"supersonic", {"SuperSonic", "Lunatic Sounds", 149}},
        {"sw", {"Solar Wind", "KyuRu☆", 128}},
        {"syf", {"韶音赋", "战场原妖精", 144}},
        {"takeTheLongWayHome", {"Take The Long Way Home", "RiraN ft. core mc", 135}},
        {"tbi", {"The Bchy Idol", "乌龟", 120}},
        {"tear", {"眼泪", "Tuno桐音", 171}},
        {"test04", {"节奏快打", "", 90}},
        {"theFourSeasons", {"LA primavera", "Antonio Vivaldi", 122}},
        {"theformula", {"The Formula", "Junk", 140}},
        {"theseus8bit", {"Theseus", "Enoch", 125}},
        {"thronesOfWorld", {"权御天下", "乌龟", 135}},
        {"timeLeap", {"Time-Leap at Saturday 10:00 PM", "litmus*", 112}},
        {"title", {"圣女战旗[La Bannière]", "跳蝻 (Vanguard Sound)", 129}},
        {"tme", {"The Mountain Eater", "Paul Bazooka", 118}},
        {"tooihibi", {"遠い日々", "Luna Safari", 180}},
        {"tp", {"Terminated Protocol", "KIEN", 150}},
        {"trojan", {"Trojan", "litmus*", 154}},
        {"trueWhite", {"真白な夢", "Tuno桐音", 138}},
        {"ts", {"TWINKLE STAR", "小野道", 120}},
        {"unlift", {"Unlift", "Utae", 100}},
        {"unshakable", {"Unshakable", "RiraN", 110}},
        {"vrc", {"ViR to ReaL -Connected-", "祈inory&流月", 105}},
        {"wangxiangzheng1", {"妄想症一重加害", "DELA", 150}},
        {"wangxiangzheng10", {"十重告别", "DELA_P，崩坏Sovietsy", 194}},
        {"wangxiangzheng2", {"妄想症二重变革", "DELA", 145}},
        {"wangxiangzheng3", {"妄想症三重爱恋", "DELA", 158}},
        {"wangxiangzheng4", {"妄想症四重罪孽", "DELA", 156}},
        {"wangxiangzheng5", {"妄想症五重空洞", "DELA", 136}},
        {"wangxiangzheng6", {"妄想症六重不忠", "DELA", 161}},
        {"wangxiangzheng7", {"妄想症七重痼病", "DELA", 165}},
        {"wangxiangzheng8", {"妄想症八重回归", "DELA", 138}},
        {"wangxiangzheng9", {"妄想症九重现实", "DELA", 151}},
        {"wanshenji", {"万神纪", "海鲜面&T-L-S&司鼓君", 195}},
        {"weapon", {"I AM WEAPON", "Paul Bazooka", 118}},
        {"welcome", {"WELCOME!", "", 120}},
        {"wenziyouxi", {"文字游戏", "", 120}},
        {"whenImAwake", {"当我醒来", "Tuno桐音", 159}},
        {"whenYoureAway", {"When You're Away", "P4koo", 146}},
        {"will", {"Lost Memories[WILL:美好世界]", "小旭音乐&希望索任合资", 152}},
        {"witch", {"μάγισσα", "CPSQUQI", 142}},
        {"xiaojiuhu", {"欢迎光临", "Eurico", 145}},
        {"xingjiang", {"星降る夜のアデニウム", "Yunomi feat. nicamoq", 159}},
        {"xingqiu", {"绘卷里的星球[三色绘恋 ED]", "丸山公詳(project  lights)", 117}},
        {"xingzhiyishi", {"星之伊始", "天钦", 120}},
        {"xuanfeng", {"旋风 -tsumujikaze-", "street", 153}},
        {"xunluobing", {"巡逻兵进行曲", "Frank Meacham", 123}},
        {"ybyb", {"一半一半", "鸟爷", 135}},
        {"ycz", {"依存症", "阿良良木健", 136}},
        {"you", {"YOU", "Blacklist&St.K4N3", 156}},
        {"yourmind", {"Your Mind", "Roy Mikelate", 124}},
        {"yueyuanzhiye", {"月圆之夜[月下狂想曲]", "", 125}},
        {"yuyan", {"寓言预见遇见你的那刻", "小野道ono", 120}},
        {"zangge", {"葬歌", "ilem", 146}},
        {"zhonghuamoshuiniang", {"中华墨水娘", "純白P", 144}},
        {"zhonghuaniantuniang", {"中华粘土娘", "純白P", 157}},
        {"zhonghuashuojinniang", {"中华铄金娘", "純白P", 137}},
        {"zhonghuayuanmuniang", {"中华缘木娘", "純白P", 147}},
        {"zhonghuazhuhuoniang", {"中华烛火娘", "純白P", 129}},
        {"zombieDance", {"僵尸舞", "ilem&iKz", 121}},
        {"Aspectaclelikestarlight", {"☆をかけるスペクタクル", "ああああ", 134}},
        {"Dongfenghu", {"東風狐々(こちこんこん)", "WABI", 147}},
        {"Elctromagneticstorm", {"Elctromagnetic Storm", "NCES", 172}},
        {"Freezingbloom", {"Freezing Bloom", "Reku Mochizuki", 151}},
        {"Lifeisharmony", {"Life is HARMONY", "Junk", 135}},
        {"Mechmore", {"Mech Core", "HJLL", 132}},
        {"Neonfragment", {"Neon Fragment", "technoplanet", 146}},
        {"Outliers", {"Outliers", "Xyris", 142}},
        {"Phantomhunter", {"Phantom Hunter", "M-UE VS.brz1128", 138}},
        {"Pixelmarch", {"Pixel March", "Wolfnight狼夜", 166}},
        {"Regression", {"Re[gression]", "Jun Kuroda", 150}},
        {"Returnfromsilence", {"Return From Silence", "s9ryne", 173}},
        {"Returntothenastra", {"RE:TURN TO THE ASTRA", "Rabbit House", 151}},
        {"Shiranui", {"SHIRANUI", "Junk", 124}},
        {"Titanblaze", {"TITANBLAZE", "Xyris", 132}},
        {"Totaleclipse", {"Total eclipse", "LV.4", 185}},
        {"Unhealthy", {"Unhealthy", "RiraN", 142}},
        {"Xalvation", {"Xalvation", "Reku Mochizuki", 124}},
        {"Xilvane", {"Xilvane", "Tatsh", 131}},
        {"quasar", {"quasar", "ARForest", 135}},
    };
}
